# Memory - Anti-Regression Knowledge

This file is auto-generated by the `ws-self-learning` skill. DO NOT edit this file directly.
To add new learnings, create a separate markdown file under `{sharedDir}/memory/` and run:
  node {skillsRoot}/ws-self-learning/scripts/self_learning.cjs --compile

---
