#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const {
  resolveConsumerContext,
  toRepoRelative,
} = require('../../ws-shared/scripts/resolve_consumer_root.cjs');

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token === '--compile' || token === '-c') args.compile = true;
    else if (token === '--query' || token === '-q') args.query = argv[++i];
    else if (token === '--match-paths' || token === '-m') {
      args.matchPaths = [];
      while (i + 1 < argv.length && !argv[i + 1].startsWith('--')) args.matchPaths.push(argv[++i]);
    } else if (token === '--repo-root') args.repoRoot = argv[++i];
    else throw new Error(`unknown argument: ${token}`);
  }
  if (![args.compile, args.query, args.matchPaths].filter(Boolean).length) throw new Error('choose --compile, --query, or --match-paths');
  return args;
}

function field(text, names) {
  const escaped = names.map((name) => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
  return text.match(new RegExp(`^- \\*\\*(?:${escaped})\\*\\*:\\s*(.*)$`, 'mi'))?.[1].trim().replace(/^`|`$/g, '') || '';
}

function parseEntry(file) {
  const text = fs.readFileSync(file, 'utf8').replace(/\r\n?/g, '\n');
  const header = text.match(/^###\s+\[(\d{4}-\d{2}-\d{2})\]\s*(.+)$/m);
  const fallback = path.basename(file, '.md').match(/^(\d{4}-\d{2}-\d{2})[-_](.+)$/);
  return {
    file: path.basename(file),
    date: header?.[1] || fallback?.[1] || '1970-01-01',
    title: header?.[2]?.trim() || fallback?.[2]?.replace(/[-_]/g, ' ') || path.basename(file, '.md'),
    layer: field(text, ['Layer']),
    module: field(text, ['Module']),
    severity: field(text, ['Severity']),
    pathPattern: field(text, ['PathPattern', 'Path Pattern', 'PathPatterns', 'Path', 'Paths']),
    scenario: field(text, ['Scenario / Context', 'Scenario/Context', 'Context', 'Scenario']),
    doNot: field(text, ['DO NOT', 'Do Not', 'DO_NOT', 'Trap Avoided']),
    instead: field(text, ['INSTEAD DO', 'Instead Do', 'INSTEAD_DO', 'Solution']),
    text,
  };
}

function entries(memoryDir) {
  if (!fs.existsSync(memoryDir)) return [];
  return fs.readdirSync(memoryDir)
    .filter((name) => name.endsWith('.md') && !name.startsWith('.'))
    .map((name) => parseEntry(path.join(memoryDir, name)))
    .sort((a, b) => b.date.localeCompare(a.date) || b.title.localeCompare(a.title));
}

function compile(context, memoryDir, output) {
  fs.mkdirSync(memoryDir, { recursive: true });
  const header = [
    '# Memory - Anti-Regression Knowledge',
    '',
    'This file is auto-generated by the `ws-self-learning` skill. DO NOT edit this file directly.',
    'To add new learnings, create a separate markdown file under `{sharedDir}/memory/` and run:',
    '  node {skillsRoot}/ws-self-learning/scripts/self_learning.cjs --compile',
    '',
    '---',
  ];
  const blocks = entries(memoryDir).map((entry) => [
    '',
    `### [${entry.date}] ${entry.title}`,
    entry.layer && `- **Layer**: \`${entry.layer}\``,
    entry.module && `- **Module**: \`${entry.module}\``,
    entry.severity && `- **Severity**: \`${entry.severity}\``,
    entry.pathPattern && `- **PathPattern**: \`${entry.pathPattern}\``,
    entry.scenario && `- **Scenario / Context**: ${entry.scenario}`,
    entry.doNot && `- **DO NOT**: ${entry.doNot}`,
    entry.instead && `- **INSTEAD DO**: ${entry.instead}`,
  ].filter(Boolean).join('\n'));
  fs.writeFileSync(output, `${header.join('\n')}${blocks.join('\n')}\n`, 'utf8');
  process.stdout.write(`Compiled ${blocks.length} memory entries into ${toRepoRelative(context.repoRoot, output, { allowOutside: true })}\n`);
}

function globMatch(pattern, value) {
  const expression = pattern
    .replace(/\\/g, '/')
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*\*/g, '\0')
    .replace(/\*/g, '[^/]*')
    .replace(/\0/g, '.*');
  return new RegExp(`^${expression}$`, 'i').test(value);
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const context = resolveConsumerContext({ repoRoot: args.repoRoot, scriptFile: __filename, skillId: 'ws-self-learning' });
  const memoryDir = path.join(context.sharedDir, 'memory');
  const output = path.join(context.sharedDir, 'MEMORY.md');
  if (args.compile) return compile(context, memoryDir, output);

  const all = entries(memoryDir);
  const matches = args.query
    ? all.filter((entry) => entry.text.toLowerCase().includes(args.query.toLowerCase()))
    : all.filter((entry) => {
        const patterns = entry.pathPattern.split(/[,;]/).map((item) => item.trim().replace(/^`|`$/g, '')).filter(Boolean);
        return args.matchPaths.some((candidate) => patterns.some((pattern) => globMatch(pattern, candidate.replace(/\\/g, '/')) || candidate.includes(pattern)));
      });
  if (!matches.length) {
    process.stdout.write('No matching memory entries found.\n');
    return;
  }
  for (const entry of matches) {
    process.stdout.write(`[${entry.date}] ${entry.title} (${entry.file})\n`);
    process.stdout.write(`Severity=${entry.severity || 'unspecified'} PathPattern=${entry.pathPattern || 'n/a'}\n`);
    process.stdout.write(`DO NOT: ${entry.doNot || 'n/a'}\nINSTEAD DO: ${entry.instead || 'n/a'}\n`);
  }
}

try {
  main();
} catch (error) {
  process.stderr.write(`ERROR: ${error.message}\n`);
  process.exitCode = 1;
}
