#!/usr/bin/env python3
"""
Configure / validate shared autoload.md Always-applied paths and optional root AGENTS.md.

Usage:
  python configure_autoload.py --set-autoload true|false [--repo-root DIR] [--dry-run]
  python configure_autoload.py --write-autoload [--repo-root DIR] [--global-skills-root DIR]
  python configure_autoload.py --write-root-agents [--repo-root DIR] [--global-skills-root DIR]
  python configure_autoload.py --check [--repo-root DIR] [--global-skills-root DIR] [--json]
  python configure_autoload.py --emit-paths [--repo-root DIR] [--global-skills-root DIR] [--json]

`--set-autoload` may combine with `--write-autoload` / `--write-root-agents` (typical true path).

Never writes absolute filesystem paths into markdown. Prefer project-local
`.agents/skills/...` when SKILL.md exists there; else `{globalSkillsRoot}/...`.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path


def ensure_utf8_stdio() -> None:
    os.environ["PYTHONIOENCODING"] = "utf-8"
    for stream in (sys.stdin, sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if not callable(reconfigure):
            continue
        try:
            reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            try:
                reconfigure(errors="replace")
            except Exception:
                pass


ensure_utf8_stdio()

DEFAULT_ALWAYS_APPLIED: list[tuple[str, str]] = [
    ("ws-senior-developer", "Every prompt — delivery gate / Code review proof"),
    ("ws-self-learning", "Every mutating task — MEMORY consult + trap write"),
    ("ws-patterns-backend", "Backend tasks — backend.md consult + pattern write"),
    ("ws-patterns-frontend", "Frontend tasks — frontend.md consult + pattern write"),
    ("ws-changelog", "Every task completion — append-only history"),
    ("ws-fable-method", "Every prompt — structured investigate/act/verify when non-trivial"),
    ("ws-tdah", "Every prompt — action-first shape + judgment"),
]

# Author-machine absolute paths (Windows drive, UNC, POSIX home/opt). Never emit these.
# Do not treat URL schemes (https://) as Windows drives — require a non-letter before the drive letter.
ABS_PATH_RE = re.compile(
    r"(?:"
    r"(?<![A-Za-z0-9])[A-Za-z]:[\\/]"  # C:\… or C:/… (not https://)
    r"|\\\\[^\\\s`\"']+"  # UNC \\server\share
    r"|/(?:Users|home|opt)/"  # common author-machine POSIX roots
    r")"
)
SKILL_ROW_RE = re.compile(
    r"^\|\s*`(?P<id>ws-[a-z0-9-]+)`\s*\|\s*(?P<path>[^|]+)\|\s*(?P<trigger>[^|]+)\|\s*$",
    re.MULTILINE,
)


def default_repo_root() -> Path:
    """Consumer project being configured = process cwd (not the skill install tree)."""
    return Path.cwd().resolve()


GENERATED_MARKER = "<!-- generated by configure_autoload.py -->"
SHARED_CONFIG_REL = Path(".agents") / "skills" / "ws-shared" / "config.json"
SHARED_CONFIG_EXAMPLE_REL = Path(".agents") / "skills" / "ws-shared" / "config.json.example"


def load_config_json(repo_root: Path) -> dict | None:
    """Read project ws-shared/config.json; None if missing or invalid."""
    path = repo_root / SHARED_CONFIG_REL
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    return data


def resolve_effective_autoload(repo_root: Path) -> bool:
    """True only when config exists and defaults.autoload is JSON boolean true."""
    data = load_config_json(repo_root)
    if data is None:
        return False
    defaults = data.get("defaults")
    if not isinstance(defaults, dict):
        return False
    return defaults.get("autoload") is True


def set_autoload(repo_root: Path, value: bool, dry_run: bool = False) -> dict:
    """Ensure config.json exists, set defaults.autoload, write utf-8 JSON."""
    config_path = repo_root / SHARED_CONFIG_REL
    example_path = repo_root / SHARED_CONFIG_EXAMPLE_REL
    created_from_example = False

    if not config_path.is_file():
        if not example_path.is_file():
            raise SystemExit(
                f"ERROR: missing {config_path.as_posix()} and example "
                f"{example_path.as_posix()} (install hub / copy template)"
            )
        if not dry_run:
            config_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(example_path, config_path)
        created_from_example = True

    data = load_config_json(repo_root)
    if data is None and dry_run and created_from_example:
        try:
            data = json.loads(example_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError):
            data = None
    if data is None:
        raise SystemExit(f"ERROR: could not read or parse {config_path.as_posix()}")

    defaults = data.get("defaults")
    if not isinstance(defaults, dict):
        defaults = {}
        data["defaults"] = defaults
    defaults["autoload"] = bool(value)

    written = False
    if not dry_run:
        config_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        written = True

    return {
        "configPath": str(config_path.as_posix()),
        "autoload": bool(value),
        "written": written,
        "createdFromExample": created_from_example,
    }


def resolve_global_skills_root(explicit: str | None) -> Path:
    if explicit:
        return Path(explicit).expanduser().resolve()
    env = os.environ.get("WORKFLOW_SKILLS_GLOBAL_DIR", "").strip()
    if env:
        return Path(env).expanduser().resolve()
    return (Path.home() / ".agents" / "skills").resolve()


def emit_skill_path(
    repo_root: Path,
    skill_id: str,
    *,
    skills_root_rel: str = ".agents/skills",
    global_skills_root: Path | None = None,
) -> tuple[str, bool]:
    """Return (portable path form, missing). Never absolute."""
    local_skill = repo_root / skills_root_rel / skill_id / "SKILL.md"
    if local_skill.is_file():
        return f".agents/skills/{skill_id}/SKILL.md", False

    groot = global_skills_root or resolve_global_skills_root(None)
    global_skill = groot / skill_id / "SKILL.md"
    if global_skill.is_file():
        return f"{{globalSkillsRoot}}/{skill_id}/SKILL.md", False

    return f"{{skillsRoot}}/{skill_id}/SKILL.md", True


def default_always_applied_membership() -> list[dict]:
    """Default Always-applied skill ids + triggers (membership seed)."""
    return [{"skill": skill_id, "trigger": trigger} for skill_id, trigger in DEFAULT_ALWAYS_APPLIED]


def membership_from_existing_rows(rows: list[dict]) -> list[dict]:
    """Preserve consumer membership/triggers; drop empty/invalid rows."""
    out: list[dict] = []
    seen: set[str] = set()
    for row in rows:
        skill_id = (row.get("skill") or "").strip()
        if not skill_id.startswith("ws-") or skill_id in seen:
            continue
        seen.add(skill_id)
        trigger = (row.get("trigger") or "").strip() or "Every prompt"
        out.append({"skill": skill_id, "trigger": trigger})
    return out


def build_always_applied_table(
    repo_root: Path,
    *,
    global_skills_root: Path | None = None,
    membership: list[dict] | None = None,
) -> tuple[str, list[dict]]:
    rows: list[str] = [
        "| Skill | Path | Trigger |",
        "|-------|------|---------|",
    ]
    meta: list[dict] = []
    members = membership if membership is not None else default_always_applied_membership()
    for member in members:
        skill_id = member["skill"]
        trigger = member["trigger"]
        path_form, missing = emit_skill_path(
            repo_root, skill_id, global_skills_root=global_skills_root
        )
        rows.append(f"| `{skill_id}` | `{path_form}` | {trigger} |")
        meta.append({"skill": skill_id, "path": path_form, "missing": missing, "trigger": trigger})
    return "\n".join(rows) + "\n", meta


def ensure_autoload_md(
    repo_root: Path,
    *,
    global_skills_root: Path | None = None,
    dry_run: bool = False,
) -> dict:
    shared = repo_root / ".agents" / "skills" / "ws-shared"
    autoload_path = shared / "autoload.md"
    if not autoload_path.is_file():
        raise SystemExit(f"ERROR: missing {autoload_path} (install hub / copy template)")

    text = autoload_path.read_text(encoding="utf-8")
    existing = parse_always_applied_rows(text)
    preserved = membership_from_existing_rows(existing)
    membership = preserved if preserved else default_always_applied_membership()
    table, meta = build_always_applied_table(
        repo_root,
        global_skills_root=global_skills_root,
        membership=membership,
    )

    # Replace Always-applied markdown table (first table after heading).
    # Do not use DOTALL on row matches — otherwise `|.*|` can span past the table.
    pattern = re.compile(
        r"(## Always-applied skills\r?\n(?:.*\r?\n)*?)"
        r"(\| Skill \| Path \| Trigger \|\r?\n\|[-| ]+\|\r?\n(?:\|[^\r\n]*\|\r?\n)+)",
    )
    match = pattern.search(text)
    if not match:
        raise SystemExit("ERROR: could not find Always-applied skills table in autoload.md")

    new_text = text[: match.start(2)] + table + text[match.end(2) :]
    if "ws-configure-project" in new_text and "when that section is implemented" in new_text:
        new_text = new_text.replace(
            "Customize the Always-applied table per project when needed (or via `ws-configure-project` when that section is implemented).",
            "Customize the Always-applied table per project when needed (or via `ws-configure-project --section autoload`).",
        )

    written = False
    if new_text != text and not dry_run:
        autoload_path.write_text(new_text, encoding="utf-8")
        written = True

    return {
        "autoloadPath": str(autoload_path.as_posix()),
        "written": written,
        "changed": new_text != text,
        "skills": meta,
        "preservedMembership": bool(preserved),
    }


ROOT_AGENTS_TEMPLATE = """# AGENTS.md — Consumer root override

**Audience: agents.** Thin pointer only. Full consumer hub: [`.agents/skills/ws-shared/AGENTS.md`](.agents/skills/ws-shared/AGENTS.md).

## Autoload (Always-applied)

Load **every** skill listed in [`.agents/skills/ws-shared/autoload.md`](.agents/skills/ws-shared/autoload.md) § Always-applied skills on every prompt (unless the user opted out for that skill).

When both this file and `.agents/skills/ws-shared/AGENTS.md` load, **this root file wins** for autoload membership of those skills (intentional consumer root override over shared-hub on-demand defaults).

### Resolved paths

{table}

## Specs progressive disclosure

When the user mentions specs / plans / Spec-to-PR / `index.PRD` without naming a skill, load `autoload.md` § Specs vocabulary and § Specs skill router, then load **only** the matching skill.

## Precedence (highest first)

1. Explicit user instructions (current turn)
2. This root `AGENTS.md` (autoload membership via `autoload.md`)
3. `.agents/skills/ws-shared/AGENTS.md` (consumer hub)
4. Design / spec / architecture constraints
"""


def write_root_agents(
    repo_root: Path,
    *,
    global_skills_root: Path | None = None,
    dry_run: bool = False,
    force: bool = False,
) -> dict:
    # Prefer Always-applied membership from autoload.md when present.
    shared_autoload = repo_root / ".agents" / "skills" / "ws-shared" / "autoload.md"
    membership = default_always_applied_membership()
    if shared_autoload.is_file():
        preserved = membership_from_existing_rows(
            parse_always_applied_rows(shared_autoload.read_text(encoding="utf-8"))
        )
        if preserved:
            membership = preserved

    table_lines = [
        "| Skill | Path |",
        "|-------|------|",
    ]
    meta: list[dict] = []
    for member in membership:
        skill_id = member["skill"]
        path_form, missing = emit_skill_path(
            repo_root, skill_id, global_skills_root=global_skills_root
        )
        table_lines.append(f"| `{skill_id}` | `{path_form}` |")
        meta.append({"skill": skill_id, "path": path_form, "missing": missing})

    body = GENERATED_MARKER + "\n" + ROOT_AGENTS_TEMPLATE.format(table="\n".join(table_lines))
    if contains_absolute_path(body):
        raise SystemExit("ERROR: refused to write root AGENTS.md with absolute paths")

    dest = repo_root / "AGENTS.md"
    backed_up = False
    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            if not force:
                raise SystemExit(
                    "ERROR: root AGENTS.md exists and is not the generated thin pointer; "
                    "pass --force to overwrite (a .bak copy is written)"
                )
            if not dry_run:
                shutil.copy2(dest, dest.with_suffix(".md.bak"))
                backed_up = True

    written = False
    if not dry_run:
        dest.write_text(body, encoding="utf-8", newline="\n")
        written = True

    return {
        "rootAgentsPath": "AGENTS.md",
        "written": written,
        "backedUp": backed_up,
        "skills": meta,
    }


def contains_absolute_path(text: str) -> bool:
    """Detect author-machine absolute paths in markdown (Windows, UNC, POSIX roots)."""
    for line in text.splitlines():
        if ABS_PATH_RE.search(line):
            return True
    return False


def path_targets_skill(path_form: str, skill_id: str) -> bool:
    """True when the portable path form names the same skill id as the row."""
    normalized = path_form.strip().replace("\\", "/").rstrip("/")
    # Accept …/ws-<id>/SKILL.md or …/ws-<id> (folder form).
    if normalized.endswith("/SKILL.md"):
        normalized = normalized[: -len("/SKILL.md")]
    leaf = normalized.rsplit("/", 1)[-1]
    return leaf == skill_id


def parse_always_applied_rows(text: str) -> list[dict]:
    rows: list[dict] = []
    in_section = False
    for line in text.splitlines():
        if line.startswith("## Always-applied"):
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if not in_section:
            continue
        m = SKILL_ROW_RE.match(line)
        if not m:
            continue
        skill_id = m.group("id")
        path_raw = m.group("path").strip().strip("`").strip()
        trigger = m.group("trigger").strip()
        rows.append({"skill": skill_id, "path": path_raw, "trigger": trigger})
    return rows


def path_form_ok(path_form: str) -> bool:
    if contains_absolute_path(f"`{path_form}`"):
        return False
    if path_form.startswith("{skillsRoot}/") or path_form.startswith("{globalSkillsRoot}/"):
        return True
    if path_form.startswith(".agents/skills/"):
        return True
    return False


def _append_effective_autoload_root_findings(
    findings: list[dict],
    *,
    effective: bool,
    root_agents: Path,
    root_text: str | None,
) -> None:
    """When defaults.autoload is true, require root AGENTS.md with autoload.md reference."""
    if not effective:
        return
    fix = "Run ws-configure-project --section autoload"
    if not root_agents.is_file():
        findings.append(
            {
                "severity": "critical",
                "file": "AGENTS.md",
                "message": (
                    "defaults.autoload is true but root AGENTS.md is missing"
                ),
                "fix": fix,
            }
        )
        return
    text = root_text if root_text is not None else root_agents.read_text(encoding="utf-8")
    if "autoload.md" not in text:
        findings.append(
            {
                "severity": "critical",
                "file": "AGENTS.md",
                "message": (
                    "defaults.autoload is true but root AGENTS.md does not instruct "
                    "loading Always-applied skills via autoload.md"
                ),
                "fix": fix,
            }
        )


def check_autoload(
    repo_root: Path,
    *,
    global_skills_root: Path | None = None,
) -> dict:
    findings: list[dict] = []
    shared = repo_root / ".agents" / "skills" / "ws-shared"
    autoload_path = shared / "autoload.md"
    root_agents = repo_root / "AGENTS.md"
    effective = resolve_effective_autoload(repo_root)
    root_text: str | None = (
        root_agents.read_text(encoding="utf-8") if root_agents.is_file() else None
    )

    if not autoload_path.is_file():
        _append_effective_autoload_root_findings(
            findings,
            effective=effective,
            root_agents=root_agents,
            root_text=root_text,
        )
        critical = sum(1 for f in findings if f["severity"] == "critical")
        return {
            "ok": critical == 0,
            "findings": findings,
            "note": "autoload.md absent — skip Always-applied path checks",
            "rootAgentsPresent": root_agents.is_file(),
            "effectiveAutoload": effective,
            "autoloadPresent": False,
        }

    text = autoload_path.read_text(encoding="utf-8")
    if contains_absolute_path(text):
        findings.append(
            {
                "severity": "critical",
                "file": ".agents/skills/ws-shared/autoload.md",
                "message": "Absolute filesystem path detected; use relative or declared tokens only",
                "fix": "Run ws-configure-project --section autoload / configure_autoload.py --write-autoload",
            }
        )

    for row in parse_always_applied_rows(text):
        if not path_form_ok(row["path"]):
            findings.append(
                {
                    "severity": "warning",
                    "file": ".agents/skills/ws-shared/autoload.md",
                    "message": f"Always-applied path for `{row['skill']}` is not portable: {row['path']}",
                    "fix": "Use `.agents/skills/...` or `{skillsRoot}` / `{globalSkillsRoot}` tokens",
                }
            )
        elif not path_targets_skill(row["path"], row["skill"]):
            findings.append(
                {
                    "severity": "warning",
                    "file": ".agents/skills/ws-shared/autoload.md",
                    "message": (
                        f"Always-applied path for `{row['skill']}` points at a different skill: "
                        f"{row['path']}"
                    ),
                    "fix": (
                        f"Point the path at `{row['skill']}/SKILL.md` "
                        "(or run configure_autoload.py --write-autoload)"
                    ),
                }
            )
        local = repo_root / ".agents" / "skills" / row["skill"] / "SKILL.md"
        groot = global_skills_root or resolve_global_skills_root(None)
        global_skill = groot / row["skill"] / "SKILL.md"
        if not local.is_file() and not global_skill.is_file():
            findings.append(
                {
                    "severity": "warning",
                    "file": ".agents/skills/ws-shared/autoload.md",
                    "message": f"Always-applied skill `{row['skill']}` missing under skillsRoot and globalSkillsRoot",
                    "fix": f"Install `{row['skill']}` or remove the Always-applied row",
                }
            )

    if root_text is not None:
        if contains_absolute_path(root_text):
            findings.append(
                {
                    "severity": "critical",
                    "file": "AGENTS.md",
                    "message": "Absolute filesystem path detected in root AGENTS.md",
                    "fix": "Regenerate via configure_autoload.py --write-root-agents",
                }
            )
        # Dual-hub override: referencing autoload.md is intentional — no finding.

    _append_effective_autoload_root_findings(
        findings,
        effective=effective,
        root_agents=root_agents,
        root_text=root_text,
    )

    critical = sum(1 for f in findings if f["severity"] == "critical")
    return {
        "ok": critical == 0,
        "findings": findings,
        "rootAgentsPresent": root_agents.is_file(),
        "autoloadPresent": True,
        "effectiveAutoload": effective,
        "dualHubOverrideOk": (
            (not root_agents.is_file())
            or (root_text is not None and "autoload.md" in root_text)
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=None, help="Consumer / package repo root")
    parser.add_argument(
        "--global-skills-root",
        default=None,
        help="Override {globalSkillsRoot} (default WORKFLOW_SKILLS_GLOBAL_DIR or ~/.agents/skills)",
    )
    parser.add_argument("--write-autoload", action="store_true")
    parser.add_argument("--write-root-agents", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--emit-paths", action="store_true")
    parser.add_argument(
        "--set-autoload",
        choices=("true", "false"),
        default=None,
        help="Persist defaults.autoload in project config.json (true|false)",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite non-generated root AGENTS.md (writes AGENTS.md.bak first)",
    )
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve() if args.repo_root else default_repo_root()
    groot = (
        Path(args.global_skills_root).expanduser().resolve()
        if args.global_skills_root
        else resolve_global_skills_root(None)
    )

    if not any(
        [
            args.write_autoload,
            args.write_root_agents,
            args.check,
            args.emit_paths,
            args.set_autoload is not None,
        ]
    ):
        parser.error(
            "Choose --set-autoload, --write-autoload, --write-root-agents, "
            "--check, or --emit-paths"
        )

    out: dict = {"repoRoot": str(repo_root.as_posix())}

    if args.emit_paths:
        _, meta = build_always_applied_table(repo_root, global_skills_root=groot)
        out["skills"] = meta

    # Root write before --set-autoload true so a refused overwrite cannot leave
    # defaults.autoload=true with a missing/incomplete root (harness critical).
    if args.write_autoload:
        out["autoload"] = ensure_autoload_md(
            repo_root, global_skills_root=groot, dry_run=args.dry_run
        )

    if args.write_root_agents:
        out["rootAgents"] = write_root_agents(
            repo_root,
            global_skills_root=groot,
            dry_run=args.dry_run,
            force=args.force,
        )

    if args.set_autoload is not None:
        out["setAutoload"] = set_autoload(
            repo_root,
            args.set_autoload == "true",
            dry_run=args.dry_run,
        )

    if args.check:
        out["check"] = check_autoload(repo_root, global_skills_root=groot)

    if args.json:
        print(json.dumps(out, indent=2, ensure_ascii=False))
    else:
        if "setAutoload" in out:
            s = out["setAutoload"]
            print(
                f"defaults.autoload={s['autoload']} written={s['written']} "
                f"createdFromExample={s['createdFromExample']}"
            )
        if args.emit_paths:
            for row in out.get("skills", []):
                flag = " MISSING" if row["missing"] else ""
                print(f"{row['skill']}: {row['path']}{flag}")
        if "autoload" in out:
            a = out["autoload"]
            print(f"autoload: changed={a['changed']} written={a['written']}")
        if "rootAgents" in out:
            r = out["rootAgents"]
            print(f"root AGENTS.md: written={r['written']}")
        if "check" in out:
            c = out["check"]
            print(
                f"check ok={c['ok']} findings={len(c['findings'])} "
                f"effectiveAutoload={c.get('effectiveAutoload')}"
            )
            for f in c["findings"]:
                print(f"  [{f['severity']}] {f['file']}: {f['message']}")

    if args.check and not out.get("check", {}).get("ok", True):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
