#!/usr/bin/env node
'use strict';

// Port of configure_autoload.py (ws-configure-project):
// Configure / validate shared autoload.md Always-applied paths and optional root AGENTS.md.
//
// Usage:
//   node configure_autoload.cjs --set-autoload true|false [--repo-root DIR] [--dry-run]
//   node configure_autoload.cjs --set-autoload-task-lifecycle true|false [--repo-root DIR] [--dry-run]
//   node configure_autoload.cjs --write-autoload [--repo-root DIR] [--global-skills-root DIR]
//   node configure_autoload.cjs --write-root-agents [--repo-root DIR] [--global-skills-root DIR]
//   node configure_autoload.cjs --check [--repo-root DIR] [--global-skills-root DIR] [--json]
//   node configure_autoload.cjs --emit-paths [--repo-root DIR] [--global-skills-root DIR] [--json]
//
// `--set-autoload` may combine with `--write-autoload` / `--write-root-agents` (typical true path).
//
// Never writes absolute filesystem paths into markdown. Prefer project-local
// `.agents/skills/...` when SKILL.md exists there; else `{globalSkillsRoot}/...`.

const fs = require('fs');
const os = require('os');
const path = require('path');

const DEFAULT_ALWAYS_APPLIED = [
  ['ws-senior-developer', 'Every prompt — delivery gate, surgical diffs / Code review proof'],
  ['ws-self-learning', 'Every mutating task — MEMORY consult + trap write; after each `ws-goal-fix-pr` / `ws-fix-pr` round, record reviewer/CI mistakes'],
  ['ws-tdah', 'Every prompt — action-first shape + judgment'],
  ['ws-spec-memo', 'Config preflight & bridge — wire config.json memory backends & hybrid fallback'],
  ['ws-task-lifecycle', 'Every prompt-driven product task — intake, implement, complete (required)'],
];

const ABS_PATH_RE = /(?:(?<![A-Za-z0-9])[A-Za-z]:[\\/]|\\\\[^\\\s`"']+|\/(?:Users|home|opt)\/)/;
const SKILL_ROW_RE = /^\|\s*`(ws-[a-z0-9-]+)`\s*\|\s*([^|]+)\|\s*([^|]+)\|\s*$/;

function defaultRepoRoot() {
  return path.resolve(process.cwd());
}

const GENERATED_MARKER = '<!-- generated by configure_autoload.cjs -->';
const SHARED_CONFIG_REL = path.join('.ws', 'config.json');
const SHARED_CONFIG_EXAMPLE_REL = path.join('.agents', 'skills', 'ws-shared', 'templates', 'config.json.example');
const SHARED_AUTOLOAD_REL = path.join('.ws', 'autoload.md');
const SHARED_RUNTIME_REL = path.join('.agents', 'skills', 'ws-shared', 'runtime');

function knownGlobalSkillsRoots() {
  const home = os.homedir();
  const roots = [
    resolveGlobalSkillsRoot(null),
    path.resolve(home, '.agents', 'skills'),
    path.resolve(home, '.claude', 'skills'),
    path.resolve(home, '.codex', 'skills'),
    path.resolve(home, '.gemini', 'config', 'skills'),
  ];
  return [...new Set(roots)];
}

function isGlobalSkillsRoot(p) {
  const resolved = path.resolve(p);
  return knownGlobalSkillsRoots().some((r) => r === resolved);
}

function loadConfigJson(repoRoot) {
  const p = path.join(repoRoot, SHARED_CONFIG_REL);
  if (!fs.existsSync(p)) return null;
  try {
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (!data || typeof data !== 'object') return null;
    return data;
  } catch { return null; }
}

function resolveEffectiveAutoload(repoRoot) {
  const data = loadConfigJson(repoRoot);
  if (!data) return false;
  const defaults = data.defaults;
  if (!defaults || typeof defaults !== 'object') return false;
  return defaults.autoload === true;
}

function resolveAutoloadTaskLifecycle(repoRoot) {
  const data = loadConfigJson(repoRoot);
  if (!data) return true;
  const defaults = data.defaults;
  if (!defaults || typeof defaults !== 'object') return true;
  if (!('autoloadTaskLifecycle' in defaults)) return true;
  return defaults.autoloadTaskLifecycle !== false;
}

const TASK_LIFECYCLE_ID = 'ws-task-lifecycle';
const TASK_LIFECYCLE_TRIGGER = 'Every prompt-driven product task — intake, implement, complete (required)';

function ensureTaskLifecycleMember(membership) {
  if (membership.some((r) => r.skill === TASK_LIFECYCLE_ID)) return membership;
  return [...membership, { skill: TASK_LIFECYCLE_ID, trigger: TASK_LIFECYCLE_TRIGGER }];
}

function dropTaskLifecycleMember(membership) {
  return membership.filter((r) => r.skill !== TASK_LIFECYCLE_ID);
}

function setAutoloadTaskLifecycle(repoRoot, value, dryRun = false, examplePath = null) {
  const configPath = path.join(repoRoot, SHARED_CONFIG_REL);
  examplePath = examplePath || path.join(repoRoot, SHARED_CONFIG_EXAMPLE_REL);
  let createdFromExample = false;
  if (!fs.existsSync(configPath)) {
    if (!fs.existsSync(examplePath)) {
      console.error(`ERROR: missing ${configPath} and example ${examplePath} (install hub / copy template)`);
      process.exit(1);
    }
    if (!dryRun) {
      fs.mkdirSync(path.dirname(configPath), { recursive: true });
      fs.copyFileSync(examplePath, configPath);
    }
    createdFromExample = true;
  }
  let data = loadConfigJson(repoRoot);
  if (!data && dryRun && createdFromExample) {
    try { data = JSON.parse(fs.readFileSync(examplePath, 'utf8')); } catch { data = null; }
  }
  if (!data) {
    console.error(`ERROR: could not read or parse ${configPath}`);
    process.exit(1);
  }
  if (!data.defaults || typeof data.defaults !== 'object') data.defaults = {};
  data.defaults.autoloadTaskLifecycle = Boolean(value);
  let written = false;
  if (!dryRun) {
    fs.writeFileSync(configPath, JSON.stringify(data, null, 2) + '\n', 'utf8');
    written = true;
  }
  return { configPath, autoloadTaskLifecycle: Boolean(value), autoload: data.defaults.autoload, written, createdFromExample };
}

function setAutoload(repoRoot, value, dryRun = false, examplePath = null) {
  const configPath = path.join(repoRoot, SHARED_CONFIG_REL);
  examplePath = examplePath || path.join(repoRoot, SHARED_CONFIG_EXAMPLE_REL);
  let createdFromExample = false;
  if (!fs.existsSync(configPath)) {
    if (!fs.existsSync(examplePath)) {
      console.error(`ERROR: missing ${configPath} and example ${examplePath} (install hub / copy template)`);
      process.exit(1);
    }
    if (!dryRun) {
      fs.mkdirSync(path.dirname(configPath), { recursive: true });
      fs.copyFileSync(examplePath, configPath);
    }
    createdFromExample = true;
  }
  let data = loadConfigJson(repoRoot);
  if (!data && dryRun && createdFromExample) {
    try { data = JSON.parse(fs.readFileSync(examplePath, 'utf8')); } catch { data = null; }
  }
  if (!data) {
    console.error(`ERROR: could not read or parse ${configPath}`);
    process.exit(1);
  }
  if (!data.defaults || typeof data.defaults !== 'object') data.defaults = {};
  data.defaults.autoload = Boolean(value);
  let written = false;
  if (!dryRun) {
    fs.writeFileSync(configPath, JSON.stringify(data, null, 2) + '\n', 'utf8');
    written = true;
  }
  return { configPath, autoload: Boolean(value), written, createdFromExample };
}

function resolveGlobalSkillsRoot(explicit) {
  if (explicit) return path.resolve(String(explicit).replace(/^~(?=$|[\\/])/, os.homedir()));
  const env = (process.env.WORKFLOW_SKILLS_GLOBAL_DIR || '').trim();
  if (env) return path.resolve(env.replace(/^~(?=$|[\\/])/, os.homedir()));
  return path.resolve(os.homedir(), '.agents', 'skills');
}

function resolveExecutionGlobalSkillsRoot(explicit) {
  if (explicit) return resolveGlobalSkillsRoot(explicit);
  const scriptPath = path.resolve(__filename);
  for (const root of knownGlobalSkillsRoots()) {
    if (scriptPath === root || scriptPath.startsWith(root + path.sep)) return root;
  }
  return resolveGlobalSkillsRoot(null);
}

function scriptIsGlobalSkillsInstall() {
  const scriptPath = path.resolve(__filename);
  return knownGlobalSkillsRoots().some((root) => scriptPath === root || scriptPath.startsWith(root + path.sep));
}

function resolveRuntimeSource(repoRoot, globalSkillsRoot, allowGlobalSource = false) {
  const local = path.join(repoRoot, SHARED_RUNTIME_REL);
  if (fs.existsSync(local)) return local;
  if (!allowGlobalSource && !scriptIsGlobalSkillsInstall()) return local;
  return path.join(globalSkillsRoot, 'ws-shared', 'runtime');
}

function resolveTemplateSource(repoRoot, globalSkillsRoot, allowGlobalSource = false) {
  const local = path.join(repoRoot, path.dirname(SHARED_CONFIG_EXAMPLE_REL));
  if (fs.existsSync(local)) return local;
  if (!allowGlobalSource && !scriptIsGlobalSkillsInstall()) return local;
  return path.join(globalSkillsRoot, 'ws-shared', 'templates');
}

function hubRootFor(repoRoot) {
  // Bootstrap discovery location for the hub root is always <repo>/.ws/config.json;
  // a configured pathTokens.sharedDir then relocates hub content (autoload,
  // pointer, generated consumer skills) to that root.
  let hubRel = '.ws';
  try {
    const configPath = path.join(repoRoot, '.ws', 'config.json');
    if (fs.existsSync(configPath)) {
      const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      const configured = config && config.pathTokens && config.pathTokens.sharedDir;
      if (typeof configured === 'string' && configured.trim()) hubRel = configured.trim();
    }
  } catch {
    hubRel = '.ws';
  }
  return path.resolve(repoRoot, hubRel);
}

function sharedAutoloadPath(repoRoot) {
  return path.join(hubRootFor(repoRoot), 'autoload.md');
}

function hubPointerPath(repoRoot) {
  return path.join(hubRootFor(repoRoot), 'AGENTS.md');
}

function expectedGeneratedRowPath(repoRoot, skillId) {
  return path.relative(repoRoot, path.join(hubRootFor(repoRoot), skillId, 'SKILL.md')).split(path.sep).join('/');
}

function isGeneratorManagedId(repoRoot, skillId, { globalSkillsRoot = null, allowGlobalSource = false } = {}) {
  return loadGeneratorManagedIds(repoRoot, { globalSkillsRoot, allowGlobalSource }).has(skillId);
}

function emitSkillPath(repoRoot, skillId, { skillsRootRel = '.agents/skills', globalSkillsRoot = null, allowGlobalSource = false } = {}) {
  // Hub-hosted generated consumer skills are never installed: their row points
  // at the shared-hub path (existence is checked by the membership filter).
  if (isGeneratorManagedId(repoRoot, skillId, { globalSkillsRoot, allowGlobalSource })) {
    const hubTarget = path.join(hubRootFor(repoRoot), skillId, 'SKILL.md');
    const rel = path.relative(repoRoot, hubTarget).split(path.sep).join('/');
    return [rel, !fs.existsSync(hubTarget)];
  }
  const localSkill = path.join(repoRoot, skillsRootRel, skillId, 'SKILL.md');
  if (fs.existsSync(localSkill)) return [`.agents/skills/${skillId}/SKILL.md`, false];
  const groot = globalSkillsRoot || resolveGlobalSkillsRoot(null);
  if (fs.existsSync(path.join(groot, skillId, 'SKILL.md'))) return [`{globalSkillsRoot}/${skillId}/SKILL.md`, false];
  return [`{skillsRoot}/${skillId}/SKILL.md`, true];
}

function loadExternalSkillIds(repoRoot, { globalSkillsRoot = null, allowGlobalSource = false } = {}) {
  const candidates = [path.join(repoRoot, 'bin', 'skill-dependencies.json')];
  const runtime = resolveRuntimeSource(repoRoot, globalSkillsRoot || resolveExecutionGlobalSkillsRoot(null), allowGlobalSource);
  candidates.push(path.join(runtime, 'skill-dependencies.json'));
  for (const candidate of candidates) {
    if (!fs.existsSync(candidate)) continue;
    let data;
    try { data = JSON.parse(fs.readFileSync(candidate, 'utf8')); } catch { continue; }
    const raw = data.externalSkills || [];
    if (!Array.isArray(raw)) continue;
    const ids = new Set();
    for (const item of raw) {
      if (typeof item === 'string' && item.startsWith('ws-')) ids.add(item);
      else if (item && typeof item === 'object') {
        const sid = String(item.id || '').trim();
        if (sid.startsWith('ws-')) ids.add(sid);
      }
    }
    return ids;
  }
  return new Set();
}

function loadGeneratorManagedIds(repoRoot, { globalSkillsRoot = null, allowGlobalSource = false } = {}) {
  const candidates = [path.join(repoRoot, 'bin', 'skill-dependencies.json')];
  const runtime = resolveRuntimeSource(repoRoot, globalSkillsRoot || resolveExecutionGlobalSkillsRoot(null), allowGlobalSource);
  candidates.push(path.join(runtime, 'skill-dependencies.json'));
  for (const candidate of candidates) {
    if (!fs.existsSync(candidate)) continue;
    let data;
    try { data = JSON.parse(fs.readFileSync(candidate, 'utf8')); } catch { continue; }
    const raw = data.externalSkills || [];
    if (!Array.isArray(raw)) continue;
    const ids = new Set();
    for (const item of raw) {
      if (item && typeof item === 'object' && item.generatorManaged === true) {
        const sid = String(item.id || '').trim();
        if (sid.startsWith('ws-')) ids.add(sid);
      }
    }
    return ids;
  }
  return new Set();
}

function generatorManagedTreeExists(repoRoot, skillId, globalSkillsRoot = null) {
  // Generated consumer skills are project-local hub content by definition, so
  // there is no global-skills fallback for them. Existence is resolved with the
  // same symlink-aware containment rule as the seeder: a hub body linked outside
  // the repository does not count as present.
  const target = path.join(hubRootFor(repoRoot), skillId, 'SKILL.md');
  if (!fs.existsSync(target)) return false;
  let rootReal;
  try {
    rootReal = fs.realpathSync(path.resolve(repoRoot));
  } catch {
    return false;
  }
  const targetReal = realpathLoose(target);
  return Boolean(targetReal && targetReal.startsWith(rootReal + path.sep));
}

function realpathLoose(candidate) {
  // Resolve symlinks through the deepest existing ancestor; fail closed (null)
  // for unresolvable or dangling links instead of trusting a lexical path.
  const rest = [];
  let existing = candidate;
  for (;;) {
    try {
      fs.lstatSync(existing);
      break;
    } catch {
      // keep walking up past missing leaves
    }
    rest.unshift(path.basename(existing));
    const parent = path.dirname(existing);
    if (parent === existing) return null;
    existing = parent;
  }
  try {
    return path.join(fs.realpathSync(existing), ...rest);
  } catch {
    return null;
  }
}

function dropExternalCompanionMembers(membership, repoRoot, { globalSkillsRoot = null, allowGlobalSource = false } = {}) {
  const external = loadExternalSkillIds(repoRoot, { globalSkillsRoot, allowGlobalSource });
  if (!external.size) return membership;
  const managed = loadGeneratorManagedIds(repoRoot, { globalSkillsRoot, allowGlobalSource });
  return membership.filter((row) => {
    if (!external.has(row.skill)) return true;
    return managed.has(row.skill) && generatorManagedTreeExists(repoRoot, row.skill, globalSkillsRoot);
  });
}

function renderConsumerAutoload(text, { repoRoot = null } = {}) {
  // Managed runtime/skills resolve project-local per file: a partial local
  // runtime (directory present, sibling missing) must keep the
  // {globalSkillsRoot} token for the missing file instead of pointing at a
  // local path that does not exist. A global-only consumer gets tokens for
  // every runtime link.
  const localRuntimeDir = repoRoot
    ? path.join(repoRoot, '.agents', 'skills', 'ws-shared', 'runtime')
    : null;
  const runtimePrefixFor = (rel) => (
    localRuntimeDir && rel && fs.existsSync(path.join(localRuntimeDir, rel))
      ? '../.agents/skills/ws-shared/runtime/'
      : '{globalSkillsRoot}/ws-shared/runtime/'
  );
  const skillTarget = (rel) => (
    repoRoot && fs.existsSync(path.join(repoRoot, '.agents', 'skills', rel))
      ? `../.agents/skills/${rel}`
      : `{globalSkillsRoot}/${rel}`
  );
  // Normalize previously rendered prefixes so refreshes converge (no-op when
  // the local file exists and the prefix already matches).
  text = text.replace(
    /\]\(\.\.\/\.agents\/skills\/ws-shared\/runtime\/([^)]+)\)/g,
    (match, rel) => `](${runtimePrefixFor(rel)}${rel})`,
  );
  text = text.replace(/\]\(\.\.\/\.agents\/skills\/(ws-[^)]+)\)/g, (match, rel) => `](${skillTarget(rel)})`);
  // Legacy pre-0.4.46 rendered forms: `](runtime/<file>)` and `](../ws-<id>/...)`.
  text = text.replace(/\]\(runtime\/([^)]+)\)/g, (match, rel) => `](${runtimePrefixFor(rel)}${rel})`);
  text = text.replace(/\]\(\.\.\/(ws-[^)]+)\)/g, (match, rel) => `](${skillTarget(rel)})`);
  // Global-token links re-resolve once a local runtime file exists (local-first).
  text = text.replace(
    /\]\(\{globalSkillsRoot\}\/ws-shared\/runtime\/([^)]+)\)/g,
    (match, rel) => `](${runtimePrefixFor(rel)}${rel})`,
  );
  text = text.replace(/\]\(\{globalSkillsRoot\}\/(ws-[^)]+)\)/g, (match, rel) => `](${skillTarget(rel)})`);
  for (const f of ['AGENTS.md', 'CROSS-PLATFORM.md', 'config-resolution.md', 'gates.md', 'host-dispatch.md', 'scm-provider-contract.md', 'setup.md', 'tools.md']) {
    text = text.split(`](${f})`).join(`](${runtimePrefixFor(f)}${f})`);
  }
  return text.replace(/\]\(\.\.\/\.\.\/(ws-[^)]+)\)/g, (match, rel) => `](${skillTarget(rel)})`);
}

function defaultAlwaysAppliedMembership() {
  return DEFAULT_ALWAYS_APPLIED.map(([skill, trigger]) => ({ skill, trigger }));
}

function membershipFromExistingRows(rows) {
  const out = [];
  const seen = new Set();
  for (const row of rows) {
    const skillId = String(row.skill || '').trim();
    if (!skillId.startsWith('ws-') || seen.has(skillId)) continue;
    seen.add(skillId);
    out.push({ skill: skillId, trigger: String(row.trigger || '').trim() || 'Every prompt' });
  }
  return out;
}

function buildAlwaysAppliedTable(repoRoot, { globalSkillsRoot = null, membership = null, allowGlobalSource = false } = {}) {
  const rows = ['| Skill | Path | Trigger|', '|-------|------|---------|'];
  // Note: header row below is normalized by the writer; keep exact canonical form:
  rows[0] = '| Skill | Path | Trigger |';
  const meta = [];
  const members = membership !== null ? membership : defaultAlwaysAppliedMembership();
  for (const member of members) {
    const [pathForm, missing] = emitSkillPath(repoRoot, member.skill, { globalSkillsRoot, allowGlobalSource });
    rows.push(`| \`${member.skill}\` | \`${pathForm}\` | ${member.trigger} |`);
    meta.push({ skill: member.skill, path: pathForm, missing, trigger: member.trigger });
  }
  return [rows.join('\n') + '\n', meta];
}

function ensureAutoloadMd(repoRoot, { globalSkillsRoot = null, allowGlobalSource = false, dryRun = false } = {}) {
  const autoloadPath = sharedAutoloadPath(repoRoot);
  let source = null;
  if (!fs.existsSync(autoloadPath)) {
    const runtime = resolveRuntimeSource(repoRoot, globalSkillsRoot || resolveExecutionGlobalSkillsRoot(null), allowGlobalSource);
    source = path.join(runtime, 'autoload.md');
    if (!fs.existsSync(source)) {
      console.error(`ERROR: missing ${source} (install hub runtime)`);
      process.exit(1);
    }
    if (!dryRun) {
      fs.mkdirSync(path.dirname(autoloadPath), { recursive: true });
      fs.writeFileSync(autoloadPath, renderConsumerAutoload(fs.readFileSync(source, 'utf8'), { repoRoot }), 'utf8');
    }
  }
  const text = renderConsumerAutoload(
    fs.existsSync(autoloadPath) ? fs.readFileSync(autoloadPath, 'utf8') : fs.readFileSync(source, 'utf8'),
    { repoRoot },
  );
  const existing = parseAlwaysAppliedRows(text);
  const preserved = membershipFromExistingRows(existing);
  let membership = preserved.length ? preserved : defaultAlwaysAppliedMembership();
  membership = dropExternalCompanionMembers(membership, repoRoot, { globalSkillsRoot, allowGlobalSource });
  membership = resolveAutoloadTaskLifecycle(repoRoot) ? ensureTaskLifecycleMember(membership) : dropTaskLifecycleMember(membership);
  const [table, meta] = buildAlwaysAppliedTable(repoRoot, { globalSkillsRoot, membership, allowGlobalSource });
  const pattern = /(## Always-applied skills\r?\n(?:.*\r?\n)*?)(\| Skill \| Path \| Trigger \|\r?\n\|[-| ]+\|\r?\n(?:\|[^\r\n]*\|\r?\n)+)/;
  const match = pattern.exec(text);
  if (!match) {
    console.error('ERROR: could not find Always-applied skills table in autoload.md');
    process.exit(1);
  }
  let newText = text.slice(0, match.index + match[1].length) + table + text.slice(match.index + match[0].length);
  if (newText.includes('ws-configure-project') && newText.includes('when that section is implemented')) {
    newText = newText.split('Customize the Always-applied table per project when needed (or via `ws-configure-project` when that section is implemented).').join('Customize the Always-applied table per project when needed (or via `ws-configure-project --section autoload`).');
  }
  let written = false;
  if (newText !== text && !dryRun) {
    fs.writeFileSync(autoloadPath, newText, 'utf8');
    written = true;
  }
  return { autoloadPath, written, changed: newText !== text, skills: meta, preservedMembership: Boolean(preserved.length) };
}

const LOCAL_HUB_POINTER_MD = `# Shared - Workflow Config & Consumer Data Hub (local pointer)

This project-local pointer keeps the consumer hub stable. Managed hub runtime and templates resolve from the project skills install (\`{skillsRoot}/ws-shared/\`) when present, otherwise from \`{globalSkillsRoot}/ws-shared/\`; the consumer hub never carries \`runtime/\` or \`templates/\` copies. Project consumer data lives in this folder (\`config.json\`, \`STACK.md\`, \`installed-skills.json\`); MEMORY/changelog live at their configured locations (defaults: repo-root \`MEMORY.md\` + \`memory/\`, repo-root \`CHANGELOG.md\`).

- Full hub contract: \`{skillsRoot}/ws-shared/runtime/AGENTS.md\` (global fallback \`{globalSkillsRoot}/ws-shared/runtime/AGENTS.md\`).
- Config always resolves project-local first: \`$PWD/.ws/config.json\` overrides the global hub.
- \`rules.harness\` default (\`.ws/AGENTS.md\`) resolves to this file; follow the canonical runtime link above.
`;

const ROOT_AGENTS_TEMPLATE = `# AGENTS.md — Consumer root override

**Audience: agents.** Thin pointer only. Full consumer hub: [\`.ws/AGENTS.md\`](.ws/AGENTS.md).

## Autoload (Always-applied)

Load **every** skill listed in [\`.ws/autoload.md\`](.ws/autoload.md) § Always-applied skills on every prompt (unless the user opted out for that skill).

When both this file and \`.ws/AGENTS.md\` load, **this root file wins** for autoload membership of those skills (intentional consumer root override over shared-hub on-demand defaults).

### Resolved paths

{table}

## Specs progressive disclosure

When the user mentions specs / plans / Spec-to-PR / \`index.PRD\` without naming a skill, load \`autoload.md\` § Specs vocabulary and § Specs skill router, then load **only** the matching skill.

## Precedence (highest first)

1. Explicit user instructions (current turn)
2. This root \`AGENTS.md\` (autoload membership via \`autoload.md\`)
3. \`.ws/AGENTS.md\` (consumer hub)
4. Design / spec / architecture constraints
`;

function writeRootAgents(repoRoot, { globalSkillsRoot = null, allowGlobalSource = false, dryRun = false, force = false } = {}) {
  const sharedAutoload = sharedAutoloadPath(repoRoot);
  let membership = defaultAlwaysAppliedMembership();
  if (fs.existsSync(sharedAutoload)) {
    const preserved = membershipFromExistingRows(parseAlwaysAppliedRows(fs.readFileSync(sharedAutoload, 'utf8')));
    if (preserved.length) membership = preserved;
  }
  membership = dropExternalCompanionMembers(membership, repoRoot, { globalSkillsRoot, allowGlobalSource });
  const tableLines = ['| Skill | Path |', '|-------|------|'];
  const meta = [];
  for (const member of membership) {
    const [pathForm, missing] = emitSkillPath(repoRoot, member.skill, { globalSkillsRoot, allowGlobalSource });
    tableLines.push(`| \`${member.skill}\` | \`${pathForm}\` |`);
    meta.push({ skill: member.skill, path: pathForm, missing });
  }
  const body = GENERATED_MARKER + '\n' + ROOT_AGENTS_TEMPLATE
    .split('.ws/AGENTS.md').join(path.relative(repoRoot, hubPointerPath(repoRoot)).split(path.sep).join('/'))
    .split('.ws/autoload.md').join(path.relative(repoRoot, sharedAutoloadPath(repoRoot)).split(path.sep).join('/'))
    .replace('{table}', tableLines.join('\n'));
  if (containsAbsolutePath(body)) {
    console.error('ERROR: refused to write root AGENTS.md with absolute paths');
    process.exit(1);
  }
  const dest = path.join(repoRoot, 'AGENTS.md');
  let backedUp = false;
  if (fs.existsSync(dest)) {
    const existing = fs.readFileSync(dest, 'utf8');
    if (!existing.includes(GENERATED_MARKER)) {
      if (!force) {
        console.error('ERROR: root AGENTS.md exists and is not the generated thin pointer; pass --force to overwrite (a .bak copy is written)');
        process.exit(1);
      }
      if (!dryRun) {
        fs.copyFileSync(dest, dest + '.bak');
        backedUp = true;
      }
    }
  }
  const pointerPath = hubPointerPath(repoRoot);
  let pointerWritten = false;
  if (!fs.existsSync(pointerPath)) {
    if (!dryRun) {
      fs.mkdirSync(path.dirname(pointerPath), { recursive: true });
      fs.writeFileSync(pointerPath, LOCAL_HUB_POINTER_MD, 'utf8');
      pointerWritten = true;
    }
  }
  let written = false;
  if (!dryRun) {
    fs.writeFileSync(dest, body, 'utf8');
    written = true;
  }
  return { rootAgentsPath: 'AGENTS.md', written, backedUp, hubPointerWritten: pointerWritten, skills: meta };
}

function containsAbsolutePath(text) {
  return String(text).split('\n').some((line) => ABS_PATH_RE.test(line));
}

function pathTargetsSkill(pathForm, skillId) {
  const normalized = String(pathForm).trim().replace(/\\/g, '/').replace(/\/+$/g, '');
  const noFile = normalized.endsWith('/SKILL.md') ? normalized.slice(0, -'/SKILL.md'.length) : normalized;
  return noFile.split('/').pop() === skillId;
}

function parseAlwaysAppliedRows(text) {
  const rows = [];
  const lines = String(text).split('\n');
  let inSection = false;
  for (const line of lines) {
    if (line.startsWith('## Always-applied')) { inSection = true; continue; }
    if (inSection && line.startsWith('## ')) break;
    if (!inSection) continue;
    const m = SKILL_ROW_RE.exec(line);
    if (!m) continue;
    rows.push({ skill: m[1], path: m[2].trim().replace(/^`|`$/g, '').trim(), trigger: m[3].trim() });
  }
  return rows;
}

function pathFormOk(pathForm) {
  if (containsAbsolutePath(`\`${pathForm}\``)) return false;
  if (pathForm.startsWith('{skillsRoot}/') || pathForm.startsWith('{globalSkillsRoot}/')) return true;
  if (pathForm.startsWith('.agents/skills/')) return true;
  return false;
}

function appendEffectiveAutoloadRootFindings(findings, { effective, rootAgents, rootText }) {
  if (!effective) return;
  const fix = 'Run ws-configure-project --section autoload';
  if (!fs.existsSync(rootAgents)) {
    findings.push({ severity: 'critical', file: 'AGENTS.md', message: 'defaults.autoload is true but root AGENTS.md is missing', fix });
    return;
  }
  const text = rootText !== null && rootText !== undefined ? rootText : fs.readFileSync(rootAgents, 'utf8');
  if (!text.includes('autoload.md')) {
    findings.push({ severity: 'critical', file: 'AGENTS.md', message: 'defaults.autoload is true but root AGENTS.md does not instruct loading Always-applied skills via autoload.md', fix });
  }
}

function checkAutoload(repoRoot, { globalSkillsRoot = null, allowGlobalSource = false } = {}) {
  const findings = [];
  const shared = hubRootFor(repoRoot);
  const autoloadPath = path.join(shared, 'autoload.md');
  const rootAgents = path.join(repoRoot, 'AGENTS.md');
  const effective = resolveEffectiveAutoload(repoRoot);
  const rootText = fs.existsSync(rootAgents) ? fs.readFileSync(rootAgents, 'utf8') : null;
  if (!fs.existsSync(autoloadPath)) {
    appendEffectiveAutoloadRootFindings(findings, { effective, rootAgents, rootText });
    const critical = findings.filter((f) => f.severity === 'critical').length;
    return { ok: critical === 0, findings, note: 'autoload.md absent — skip Always-applied path checks', rootAgentsPresent: fs.existsSync(rootAgents), effectiveAutoload: effective, autoloadPresent: false };
  }
  const text = fs.readFileSync(autoloadPath, 'utf8');
  if (containsAbsolutePath(text)) {
    findings.push({ severity: 'critical', file: '.ws/autoload.md', message: 'Absolute filesystem path detected; use relative or declared tokens only', fix: 'Run ws-configure-project --section autoload / configure_autoload.cjs --write-autoload' });
  }
  const externalCompanions = loadExternalSkillIds(repoRoot, { globalSkillsRoot, allowGlobalSource });
  const generatorManaged = loadGeneratorManagedIds(repoRoot, { globalSkillsRoot, allowGlobalSource });
  const managedPresent = (skill) => generatorManaged.has(skill) && generatorManagedTreeExists(repoRoot, skill, globalSkillsRoot);
  for (const row of parseAlwaysAppliedRows(text)) {
    if (generatorManaged.has(row.skill)) {
      // Hub-hosted generated consumer skills: validate the hub path, not the
      // installed-skills portability or skills-root existence rules.
      if (containsAbsolutePath(`\`${row.path}\``)) {
        findings.push({ severity: 'warning', file: '.ws/autoload.md', message: `Always-applied path for \`${row.skill}\` is not portable: ${row.path}`, fix: 'Use the hub-relative path (or run configure_autoload.cjs --write-autoload)' });
      } else if (row.path.replace(/\\/g, '/').replace(/\/+$/, '') !== expectedGeneratedRowPath(repoRoot, row.skill)) {
        findings.push({ severity: 'warning', file: '.ws/autoload.md', message: `Always-applied path for \`${row.skill}\` must point at the configured shared hub: ${row.path}`, fix: 'Run configure_autoload.cjs --write-autoload' });
      } else if (!generatorManagedTreeExists(repoRoot, row.skill, globalSkillsRoot)) {
        findings.push({ severity: 'warning', file: '.ws/autoload.md', message: `Always-applied generated skill \`${row.skill}\` missing under the shared hub`, fix: 'Run the generator (ws-patterns-generator) or remove the Always-applied row' });
      }
      continue;
    }
    if (externalCompanions.has(row.skill) && !managedPresent(row.skill)) {
      findings.push({ severity: 'warning', file: '.ws/autoload.md', message: `Always-applied lists external companion \`${row.skill}\` (not packaged here); move to External companion skills and skip when absent`, fix: 'Remove the Always-applied row; keep the optional companion section' });
      continue;
    }
    if (!pathFormOk(row.path)) {
      findings.push({ severity: 'warning', file: '.ws/autoload.md', message: `Always-applied path for \`${row.skill}\` is not portable: ${row.path}`, fix: 'Use `.agents/skills/...` or `{skillsRoot}` / `{globalSkillsRoot}` tokens' });
    } else if (!pathTargetsSkill(row.path, row.skill)) {
      findings.push({ severity: 'warning', file: '.ws/autoload.md', message: `Always-applied path for \`${row.skill}\` points at a different skill: ${row.path}`, fix: `Point the path at \`${row.skill}/SKILL.md\` (or run configure_autoload.cjs --write-autoload)` });
    }
    const local = path.join(repoRoot, '.agents', 'skills', row.skill, 'SKILL.md');
    const groot = globalSkillsRoot || resolveGlobalSkillsRoot(null);
    if (!fs.existsSync(local) && !fs.existsSync(path.join(groot, row.skill, 'SKILL.md'))) {
      findings.push({ severity: 'warning', file: '.ws/autoload.md', message: `Always-applied skill \`${row.skill}\` missing under skillsRoot and globalSkillsRoot`, fix: `Install \`${row.skill}\` or remove the Always-applied row` });
    }
  }
  if (rootText !== null) {
    if (containsAbsolutePath(rootText)) {
      findings.push({ severity: 'critical', file: 'AGENTS.md', message: 'Absolute filesystem path detected in root AGENTS.md', fix: 'Regenerate via configure_autoload.cjs --write-root-agents' });
    }
  }
  appendEffectiveAutoloadRootFindings(findings, { effective, rootAgents, rootText });
  const critical = findings.filter((f) => f.severity === 'critical').length;
  return {
    ok: critical === 0,
    findings,
    rootAgentsPresent: fs.existsSync(rootAgents),
    autoloadPresent: true,
    effectiveAutoload: effective,
    dualHubOverrideOk: (!fs.existsSync(rootAgents)) || (rootText !== null && rootText.includes('autoload.md')),
  };
}

function printHelp() {
  console.log('Usage: node configure_autoload.cjs [--repo-root DIR] [--global-skills-root DIR] [--write-autoload] [--write-root-agents] [--check] [--emit-paths] [--set-autoload true|false] [--set-autoload-task-lifecycle true|false] [--dry-run] [--force] [--json]');
}

function parseArgs(argv) {
  const o = { repoRoot: null, globalSkillsRoot: null, writeAutoload: false, writeRootAgents: false, check: false, emitPaths: false, setAutoload: null, setAutoloadTaskLifecycle: null, dryRun: false, force: false, json: false };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--help' || a === '-h') { printHelp(); process.exit(0); }
    else if (a === '--repo-root') o.repoRoot = argv[++i];
    else if (a.startsWith('--repo-root=')) o.repoRoot = a.slice(12);
    else if (a === '--global-skills-root') o.globalSkillsRoot = argv[++i];
    else if (a.startsWith('--global-skills-root=')) o.globalSkillsRoot = a.slice(20);
    else if (a === '--write-autoload') o.writeAutoload = true;
    else if (a === '--write-root-agents') o.writeRootAgents = true;
    else if (a === '--check') o.check = true;
    else if (a === '--emit-paths') o.emitPaths = true;
    else if (a === '--set-autoload') o.setAutoload = argv[++i];
    else if (a.startsWith('--set-autoload=')) o.setAutoload = a.slice(15);
    else if (a === '--set-autoload-task-lifecycle') o.setAutoloadTaskLifecycle = argv[++i];
    else if (a.startsWith('--set-autoload-task-lifecycle=')) o.setAutoloadTaskLifecycle = a.slice(30);
    else if (a === '--dry-run') o.dryRun = true;
    else if (a === '--force') o.force = true;
    else if (a === '--json') o.json = true;
    else { console.error(`unknown argument: ${a}`); process.exit(2); }
  }
  if (o.setAutoload !== null && !['true', 'false'].includes(o.setAutoload)) { console.error('argument --set-autoload: must be true|false'); process.exit(2); }
  if (o.setAutoloadTaskLifecycle !== null && !['true', 'false'].includes(o.setAutoloadTaskLifecycle)) { console.error('argument --set-autoload-task-lifecycle: must be true|false'); process.exit(2); }
  return o;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = args.repoRoot ? path.resolve(args.repoRoot) : defaultRepoRoot();
  const explicitGlobalRoot = args.globalSkillsRoot ? resolveGlobalSkillsRoot(args.globalSkillsRoot) : null;
  if (args.repoRoot === null && (isGlobalSkillsRoot(repoRoot) || (explicitGlobalRoot !== null && repoRoot === explicitGlobalRoot))) {
    console.error(`ERROR: current directory is a global skills root (${repoRoot}); pass --repo-root to target a consumer project`);
    process.exit(1);
  }
  const groot = resolveExecutionGlobalSkillsRoot(args.globalSkillsRoot);
  const allowGlobalSource = Boolean(args.globalSkillsRoot) || scriptIsGlobalSkillsInstall();
  const templateSource = resolveTemplateSource(repoRoot, groot, allowGlobalSource);
  const examplePath = path.join(templateSource, 'config.json.example');
  if (![args.writeAutoload, args.writeRootAgents, args.check, args.emitPaths, args.setAutoload !== null, args.setAutoloadTaskLifecycle !== null].some(Boolean)) {
    console.error('Choose --set-autoload, --set-autoload-task-lifecycle, --write-autoload, --write-root-agents, --check, or --emit-paths');
    process.exit(2);
  }
  const out = { repoRoot };
  if (args.emitPaths) {
    const [, meta] = buildAlwaysAppliedTable(repoRoot, { globalSkillsRoot: groot });
    out.skills = meta;
  }
  if (args.setAutoloadTaskLifecycle !== null) {
    out.setAutoloadTaskLifecycle = setAutoloadTaskLifecycle(repoRoot, args.setAutoloadTaskLifecycle === 'true', args.dryRun, examplePath);
  }
  if (args.writeAutoload) {
    out.autoload = ensureAutoloadMd(repoRoot, { globalSkillsRoot: groot, allowGlobalSource, dryRun: args.dryRun });
  }
  if (args.writeRootAgents) {
    out.rootAgents = writeRootAgents(repoRoot, { globalSkillsRoot: groot, allowGlobalSource, dryRun: args.dryRun, force: args.force });
  }
  if (args.setAutoload !== null) {
    out.setAutoload = setAutoload(repoRoot, args.setAutoload === 'true', args.dryRun, examplePath);
  }
  if (args.check) {
    out.check = checkAutoload(repoRoot, { globalSkillsRoot: groot, allowGlobalSource });
  }
  if (args.json) {
    console.log(JSON.stringify(out, null, 2));
  } else {
    if (out.setAutoload) {
      const s = out.setAutoload;
      console.log(`defaults.autoload=${s.autoload} written=${s.written} createdFromExample=${s.createdFromExample}`);
    }
    if (out.setAutoloadTaskLifecycle) {
      const t = out.setAutoloadTaskLifecycle;
      console.log(`defaults.autoloadTaskLifecycle=${t.autoloadTaskLifecycle} written=${t.written} createdFromExample=${t.createdFromExample}`);
    }
    if (args.emitPaths) {
      for (const row of out.skills || []) console.log(`${row.skill}: ${row.path}${row.missing ? ' MISSING' : ''}`);
    }
    if (out.autoload) console.log(`autoload: changed=${out.autoload.changed} written=${out.autoload.written}`);
    if (out.rootAgents) console.log(`root AGENTS.md: written=${out.rootAgents.written}`);
    if (out.check) {
      const c = out.check;
      console.log(`check ok=${c.ok} findings=${c.findings.length} effectiveAutoload=${c.effectiveAutoload}`);
      for (const f of c.findings) console.log(`  [${f.severity}] ${f.file}: ${f.message}`);
    }
  }
  if (args.check && !(out.check || {}).ok) process.exit(1);
  process.exit(0);
}

if (require.main === module) main();
module.exports = { checkAutoload, ensureAutoloadMd, writeRootAgents };

