# Memory - Anti-Regression Knowledge

This file is auto-generated by the `self-learning` skill. DO NOT edit this file directly.
To add new learnings, create a separate markdown file under `shared/memory/` and run:
  python .agents/skills/self-learning/self_learning.py --compile

---
