#!/usr/bin/env python3
"""
self_learning.py -- Compile and query memory entries to prevent merge conflicts.

Usage:
    python self_learning.py --compile
    python self_learning.py --query <keyword>
"""

import os
import re
import sys
import argparse
from pathlib import Path
from datetime import datetime


def ensure_utf8_stdio() -> None:
    """Force UTF-8 on stdio so Windows locale (cp1252) does not break text I/O."""
    for stream in (sys.stdin, sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if not callable(reconfigure):
            continue
        try:
            reconfigure(encoding="utf-8")
        except Exception:
            pass


ensure_utf8_stdio()

SKILL_DIR = Path(__file__).resolve().parent
# Consumer-owned memory lives in the shared hub (not inside this skill package).
SHARED_DIR = SKILL_DIR.parent / "shared"
MEMORY_DIR = SHARED_DIR / "memory"
COMPILED_MEMORY_PATH = SHARED_DIR / "MEMORY.md"


def parse_memory_file(file_path: Path) -> dict:
    """Parses an individual memory markdown file."""
    content = file_path.read_text(encoding="utf-8")
    
    # Try to parse date and title from the first header
    # e.g., ### [2026-07-12] AskQuestion must be FORCE-invoked at gates
    header_match = re.search(r"^###\s+\[(\d{4}-\d{2}-\d{2})\]\s*(.*)$", content, re.MULTILINE)
    
    if header_match:
        date_str = header_match.group(1)
        title = header_match.group(2).strip()
    else:
        # Fallback to parsing date from the filename: YYYY-MM-DD-something.md
        filename_match = re.match(r"^(\d{4}-\d{2}-\d{2})[_-](.*)$", file_path.stem)
        if filename_match:
            date_str = filename_match.group(1)
            title = filename_match.group(2).replace("-", " ").replace("_", " ").title()
        else:
            date_str = datetime.now().strftime("%Y-%m-%d")
            title = file_path.stem.replace("-", " ").replace("_", " ").title()
            
        # If no explicit header was matched, we might have a simple header like: ### Title
        simple_header_match = re.search(r"^###\s+(?!\[\d{4}-\d{2}-\d{2}\])(.*)$", content, re.MULTILINE)
        if simple_header_match:
            title = simple_header_match.group(1).strip()

    # Parse key-value lists
    layer = ""
    module = ""
    severity = ""
    trap_avoided = ""
    solution = ""
    
    for line in content.splitlines():
        line = line.strip()
        if line.startswith("- **Layer**:") or line.startswith("- **Layer**:"):
            layer = re.sub(r"^-\s*\*\*Layer\*\*:\s*", "", line).strip().strip("`")
        elif line.startswith("- **Module**:") or line.startswith("- **Module**:"):
            module = re.sub(r"^-\s*\*\*Module\*\*:\s*", "", line).strip().strip("`")
        elif line.startswith("- **Severity**:") or line.startswith("- **Severity**:"):
            severity = re.sub(r"^-\s*\*\*Severity\*\*:\s*", "", line).strip().strip("`")
        elif line.startswith("- **Trap Avoided**:") or line.startswith("- **Trap Avoided**:"):
            trap_avoided = re.sub(r"^-\s*\*\*Trap Avoided\*\*:\s*", "", line).strip()
        elif line.startswith("- **Solution**:") or line.startswith("- **Solution**:"):
            solution = re.sub(r"^-\s*\*\*Solution\*\*:\s*", "", line).strip()
            
    # Normalize values for standard check_memory_conflict parsing
    # If the file lacks explicit list tags but contains the content, we preserve it.
    return {
        "file_name": file_path.name,
        "date": date_str,
        "title": title,
        "layer": layer,
        "module": module,
        "severity": severity,
        "trap_avoided": trap_avoided,
        "solution": solution,
        "full_text": content.strip()
    }


def compile_memory() -> None:
    """Compiles all markdown files under memory/ into a single MEMORY.md."""
    if not MEMORY_DIR.exists():
        MEMORY_DIR.mkdir(parents=True, exist_ok=True)
        
    entries = []
    for file in MEMORY_DIR.glob("*.md"):
        if file.name.startswith("."):
            continue
        try:
            entry = parse_memory_file(file)
            entries.append(entry)
        except Exception as e:
            print(f"Warning: Failed to parse {file.name}: {e}", file=sys.stderr)
            
    # Sort entries by date descending, then title alphabetically
    entries.sort(key=lambda x: (x["date"], x["title"]), reverse=True)
    
    header = (
        "# Memory - Anti-Regression Knowledge\n\n"
        "This file is auto-generated by the `self-learning` skill. DO NOT edit this file directly.\n"
        "To add new learnings, create a separate markdown file under `shared/memory/` and run:\n"
        "  python .agents/skills/self-learning/self_learning.py --compile\n\n"
        "---"
    )
    
    body_parts = [header]
    for entry in entries:
        # Construct compiled markdown format that check_memory_conflict.py expects
        # check_memory_conflict looks for:
        # ### [Title] or ### [date] Title
        # - **Layer**: ...
        # - **Module**: ...
        # - **Severity**: ...
        lines = [f"\n### [{entry['date']}] {entry['title']}"]
        if entry["layer"]:
            lines.append(f"- **Layer**: `{entry['layer']}`")
        if entry["module"]:
            lines.append(f"- **Module**: `{entry['module']}`")
        if entry["severity"]:
            lines.append(f"- **Severity**: `{entry['severity']}`")
        if entry["trap_avoided"]:
            lines.append(f"- **Trap Avoided**: {entry['trap_avoided']}")
        if entry["solution"]:
            lines.append(f"- **Solution**: {entry['solution']}")
            
        body_parts.append("\n".join(lines))
        
    COMPILED_MEMORY_PATH.write_text("\n".join(body_parts) + "\n", encoding="utf-8")
    print(f"Successfully compiled {len(entries)} memory entries into {COMPILED_MEMORY_PATH}")


def query_memory(keyword: str) -> None:
    """Searches memory entries for matching keywords."""
    if not MEMORY_DIR.exists():
        print("No memory directory found.")
        return
        
    matches = []
    keyword_lower = keyword.lower()
    for file in MEMORY_DIR.glob("*.md"):
        if file.name.startswith("."):
            continue
        try:
            entry = parse_memory_file(file)
            if (keyword_lower in entry["title"].lower() or 
                    keyword_lower in entry["trap_avoided"].lower() or 
                    keyword_lower in entry["solution"].lower() or
                    keyword_lower in entry["layer"].lower() or
                    keyword_lower in entry["module"].lower()):
                matches.append(entry)
        except Exception:
            pass
            
    matches.sort(key=lambda x: x["date"], reverse=True)
    
    if not matches:
        print(f"No memory entries found matching '{keyword}'")
        return
        
    print(f"Found {len(matches)} matching memory entry/entries:")
    for entry in matches:
        print("=" * 60)
        print(f"[{entry['date']}] {entry['title']} ({entry['file_name']})")
        if entry['layer'] or entry['module']:
            print(f"Tags: Layer={entry['layer'] or 'N/A'}, Module={entry['module'] or 'N/A'}, Severity={entry['severity'] or 'N/A'}")
        print("-" * 60)
        print(f"Trap Avoided: {entry['trap_avoided']}")
        print(f"Solution: {entry['solution']}")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(description="Self-learning memory compilation and query utility.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--compile", "-c", action="store_true", help="Compile separate memory files into MEMORY.md")
    group.add_argument("--query", "-q", type=str, help="Query memory entries for matching keywords")
    
    args = parser.parse_args()
    
    if args.compile:
        compile_memory()
    elif args.query:
        query_memory(args.query)


if __name__ == "__main__":
    main()
