#!/usr/bin/env bash
# install-hook.sh — Install pre-commit hook for secrets leak detection
# Usage: bash .agents/skills/ws-secrets-leak-review/scripts/install-hook.sh
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || { echo "Not a git repository"; exit 1; })
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
HOOK_SRC="$SCRIPT_DIR/pre-commit.sh"
HOOK_DST="$REPO_ROOT/.git/hooks/pre-commit"

if [ ! -f "$HOOK_SRC" ]; then
  echo "Error: $HOOK_SRC not found"
  exit 1
fi

MARKER="ws-secrets-leak-review-hook"

# Recognize both current generated shims and legacy copies/symlinks installed by
# this skill before its ws-* rename. Everything else is a foreign hook.
is_our_hook() {
  if [ -L "$HOOK_DST" ]; then
    case "$(readlink "$HOOK_DST" 2>/dev/null || true)" in
      *secrets-leak-review/scripts/pre-commit.sh) return 0 ;;
    esac
    return 1
  fi
  grep -q "$MARKER" "$HOOK_DST" 2>/dev/null ||
    {
      grep -q "Secrets leak check for git pre-commit hook" "$HOOK_DST" 2>/dev/null &&
        grep -q "secrets-leak-review/scripts/secrets_scanner.sh" "$HOOK_DST" 2>/dev/null
    }
}

# Back up every foreign hook, including symlinks. Replacing one of ours must not
# litter .bak files.
if [ -e "$HOOK_DST" ] || [ -L "$HOOK_DST" ]; then
  if ! is_our_hook; then
    BACKUP="${HOOK_DST}.bak.$(date +%Y%m%d-%H%M%S)"
    echo "Backing up existing hook to $BACKUP"
    # Rename within .git/hooks instead of copying: this preserves regular files,
    # valid symlinks, and dangling symlinks even when Windows cannot create links.
    mv "$HOOK_DST" "$BACKUP"
  fi
fi

# Always write a shim that resolves the skill at run time. A direct project-local
# symlink cannot fall back to a global install if the local skill is removed.
install_shim() {
  rm -f "$HOOK_DST"
  cat << 'EOF' > "$HOOK_DST"
#!/usr/bin/env bash
# ws-secrets-leak-review-hook — generated by ws-secrets-leak-review/scripts/install-hook.sh
# Resolves the skill at run time; do not edit (re-run install-hook.sh instead).
set -euo pipefail
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
for skills_root in "$REPO_ROOT/.agents/skills" "${WORKFLOW_SKILLS_GLOBAL_DIR:-}" "${HOME:-/nonexistent}/.agents/skills"; do
  [ -n "$skills_root" ] || continue
  skills_root="${skills_root//\\//}"
  hook="$skills_root/ws-secrets-leak-review/scripts/pre-commit.sh"
  if [ -f "$hook" ]; then
    exec bash "$hook" "$@"
  elif command -v wslpath &>/dev/null; then
    wsl_hook=$(wslpath -u "$hook" 2>/dev/null || true)
    if [ -n "$wsl_hook" ] && [ -f "$wsl_hook" ]; then
      exec bash "$wsl_hook" "$@"
    fi
  fi
done
echo "[secrets-leak] ws-secrets-leak-review not installed — skipping" >&2
exit 0
EOF
  chmod +x "$HOOK_DST"
  echo "Installed pre-commit hook (runtime shim): $HOOK_DST"
}

install_shim

echo "Done. Pre-commit secrets scan active."
