#!/usr/bin/env bash
# install-hook.sh — Install pre-commit hook for secrets leak detection
# Usage: bash .agents/skills/ws-secrets-leak-review/scripts/install-hook.sh
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || { echo "Not a git repository"; exit 1; })
HOOK_SRC="$REPO_ROOT/.agents/skills/ws-secrets-leak-review/scripts/pre-commit.sh"
HOOK_DST="$REPO_ROOT/.git/hooks/pre-commit"

if [ ! -f "$HOOK_SRC" ]; then
  echo "Error: $HOOK_SRC not found"
  exit 1
fi

MARKER="ws-secrets-leak-review-hook"

# Back up only a foreign hook. Replacing one of ours must not litter .bak files.
if [ -f "$HOOK_DST" ] && [ ! -L "$HOOK_DST" ] && ! grep -q "$MARKER" "$HOOK_DST" 2>/dev/null; then
  BACKUP="${HOOK_DST}.bak.$(date +%Y%m%d-%H%M%S)"
  echo "Backing up existing hook to $BACKUP"
  cp "$HOOK_DST" "$BACKUP"
fi

# Write a shim that resolves the skill at run time. Never copy pre-commit.sh: a copy
# freezes the skill path and silently stops scanning when the skill is renamed,
# moved, or updated (Git Bash also turns `ln -s` into a copy without failing).
install_shim() {
  rm -f "$HOOK_DST"
  {
    echo '#!/usr/bin/env bash'
    echo "# $MARKER — generated by ws-secrets-leak-review/scripts/install-hook.sh"
    echo '# Resolves the skill at run time; do not edit (re-run install-hook.sh instead).'
    echo 'set -euo pipefail'
    echo 'REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0'
    echo 'for skills_root in "$REPO_ROOT/.agents/skills" "${WORKFLOW_SKILLS_GLOBAL_DIR:-${HOME:-/nonexistent}/.agents/skills}"; do'
    echo '  hook="$skills_root/ws-secrets-leak-review/scripts/pre-commit.sh"'
    echo '  [ -f "$hook" ] && exec bash "$hook" "$@"'
    echo 'done'
    echo 'echo "[secrets-leak] ws-secrets-leak-review not installed — skipping" >&2'
    echo 'exit 0'
  } > "$HOOK_DST"
  chmod +x "$HOOK_DST"
  echo "Installed pre-commit hook (shim): $HOOK_DST"
}

# Prefer a real symlink; `ln -s` can report success and still leave a plain copy.
if ln -sf "../../.agents/skills/ws-secrets-leak-review/scripts/pre-commit.sh" "$HOOK_DST" 2>/dev/null &&
  [ -L "$HOOK_DST" ]; then
  echo "Installed pre-commit hook (symlink): $HOOK_DST"
else
  install_shim
fi

echo "Done. Pre-commit secrets scan active."
