#!/usr/bin/env node
'use strict';

/**
 * compile_host_subagents.cjs — Compiles canonical workflow skills into host-specific
 * specialized subagent definitions (e.g. Cursor IDE .cursor/agents/).
 *
 * Usage:
 *   node compile_host_subagents.cjs [--repo-root DIR] [--host <cursor|claude|generic|auto>] [--clean] [--check] [--json] [--force]
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const {
  resolveConsumerContext,
  resolveSkillMdPath,
  toRepoRelative,
} = require('./resolve_consumer_root.cjs');

const SCRIPT_FILE = __filename;
const SUPPORTED_HOSTS = new Set(['cursor', 'claude', 'generic', 'auto']);
const SIGNATURE_PREFIX = '<!-- @generated by workflow-skills compile_host_subagents.cjs. DO NOT EDIT DIRECTLY.';

const STEP_SKILL_MAP = [
  { step: '00', role: 'spec-write', skill: 'ws-spec-write', productReadonly: false },
  { step: '01', role: 'plan-write', skill: 'ws-plan-write', productReadonly: false },
  { step: '02', role: 'plan-interview', skill: 'ws-plan-interview', productReadonly: false },
  { step: '03', role: 'plan-to-tasks', skill: 'ws-plan-to-tasks', productReadonly: false },
  { step: '04', role: 'implement-tasks', skill: 'ws-implement-tasks', productReadonly: false },
  { step: '05', role: 'plan-verify', skill: 'ws-plan-verify', productReadonly: true },
  { step: '06', role: 'code-review', skill: 'ws-code-review', productReadonly: false },
  { step: '07', role: 'testing', skill: 'ws-testing', productReadonly: false },
  { step: '08', role: 'ship-pr', skill: 'ws-ship-pr', productReadonly: false },
  { step: '09', role: 'fix-pr', skill: 'ws-fix-pr', productReadonly: false },
];

function normalizeNewlines(content) {
  return content.replace(/\r\n/g, '\n');
}

function sha256(content) {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

const AGENT_PREFIX_RE = /^[a-z0-9][a-z0-9-]{0,24}$/;

function validateAgentPrefix(prefix) {
  if (!AGENT_PREFIX_RE.test(prefix || '')) {
    throw new Error(
      `invalid agent prefix "${prefix}". Use 1-25 chars: lowercase letters, digits, hyphens; must start alphanumeric (e.g. "ws").`,
    );
  }
  return prefix;
}

function parseArgs(argv) {
  const options = {
    repoRoot: null,
    host: null,
    clean: false,
    check: false,
    json: false,
    force: false,
    prefix: null,
  };
  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--repo-root') options.repoRoot = argv[++i] || null;
    else if (arg === '--host') options.host = argv[++i] || null;
    else if (arg === '--prefix') options.prefix = argv[++i] || null;
    else if (arg === '--clean') options.clean = true;
    else if (arg === '--check') options.check = true;
    else if (arg === '--json') options.json = true;
    else if (arg === '--force') options.force = true;
    else if (arg === '--help' || arg === '-h') {
      options.help = true;
    }
  }
  return options;
}

function stripFrontmatter(text) {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return { frontmatter: '', body: text.trim() };
  return { frontmatter: match[1], body: match[2].trim() };
}

function resolveHostTarget(repoRoot, requestedHost, config) {
  const cfgSub = config?.defaults?.specializedSubagents || {};
  const hostVal = (requestedHost || cfgSub.targetHost || 'auto').toLowerCase().trim();

  if (!SUPPORTED_HOSTS.has(hostVal)) {
    throw new Error(`unsupported host target "${hostVal}". Supported hosts: cursor, claude, generic, auto.`);
  }

  if (hostVal === 'auto') {
    if (fs.existsSync(path.join(repoRoot, '.cursor')) || fs.existsSync(path.join(repoRoot, '.cursorrules'))) return 'cursor';
    if (fs.existsSync(path.join(repoRoot, '.claude'))) return 'claude';
    return 'generic';
  }

  return hostVal;
}

function resolveHostDirectory(repoRoot, host) {
  if (host === 'cursor') return path.join(repoRoot, '.cursor', 'agents');
  if (host === 'claude') return path.join(repoRoot, '.claude', 'agents');
  return path.join(repoRoot, '.agents', 'projections');
}

const STEP_OUTPUT_SCHEMA_BLOCK = [
  '## Step output contract (mandatory)',
  '',
  'Every run ends with a parseable `step-output` block. Do not invent field names.',
  '',
  '```json',
  '{',
  '  "status": "completed | failed | skipped",',
  '  "files_touched": ["..."],',
  '  "notes": "...",',
  '  "next_step_ready": true',
  '}',
  '```',
  '',
  'Quality gates, pre-advance validation (`validate_state.cjs --pre-advance <N>`),',
  'state recording (`update_state.cjs`), and AC ledger tracking (`ac_ledger.cjs`)',
  'remain orchestrator-enforced and mandatory regardless of this projection.',
  '',
].join('\n');

const PATH_TOKENS_NOTE_BLOCK = [
  '## Path tokens (expand before use)',
  '',
  'Brace tokens below follow the harness install contract:',
  '`{skillsRoot}` = `.agents/skills`, `{sharedDir}` = `.agents/skills/ws-shared`.',
  'Skill-relative links (`../ws-…`) and sibling links (`references/…`, `*.md`) were compiled',
  'from the canonical skill directory to point back to `.agents/skills/<skill>/`.',
  'Resolve them against `.agents/skills/<skill>/`, or prefer the repo-relative',
  '`.agents/skills/…` path stated in each compiled header.',
  '',
].join('\n');

const PRODUCT_READONLY_BLOCK = [
  '## Product-tree readonly (not host question-only mode)',
  '',
  'This verifier must not edit application product files. Host `readonly: true` is forbidden:',
  'that flag maps to a question-only session and blocks Shell.',
  '',
  'Allowed: Shell and verification aliases (tests, scans, `ac_ledger.cjs`,',
  '`scan_stack_invariants.cjs`); writes under `{plansDir}` / `{us-dir}` for the assigned',
  'report, ledger links, and telemetry.',
  '',
  'Forbidden: product source edits outside workflow artifacts; commits; push; PR merge.',
  '',
].join('\n');

function rewriteSkillLinksForProjection(body, skillId) {
  return body
    .replace(/^>\s*When this skill is loaded, output .*$/gim, '')
    .replace(/\]\(\.\.\/(ws-[^)\s]+)\)/g, '](../../.agents/skills/$1)')
    .replace(/\]\((?!https?:\/\/|mailto:|#|\/|\{|@|\.\.\/)(?:\.\/)?([^)\s]+)\)/g, `](../../.agents/skills/${skillId}/$1)`)
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function buildFrontmatter(entry, agentName, host) {
  // Keep the semantic-router surface minimal: role verbs live in `name`
  // (exact dispatch match), not in `description` (fuzzy auto-delegation match).
  // Never emit host `readonly: true`. That flag maps to a question-only
  // session that blocks Shell. Step 5 still needs tests, ledger writes, and reports.
  const lines = [
    '---',
    `name: ${agentName}`,
    `description: "Workflow step agent ${entry.step}. Internal orchestrator dispatch only; do NOT invoke autonomously."`,
  ];
  if (host === 'cursor') {
    lines.push('disable-model-invocation: true');
  }
  lines.push('---');
  return lines.join('\n');
}

function compileAgentContent(entry, skillPath, prefix, host = 'cursor') {
  const rawSkill = fs.readFileSync(skillPath, 'utf8');
  const skillHash = sha256(normalizeNewlines(rawSkill));
  const { body } = stripFrontmatter(rawSkill);
  const agentName = `${prefix}-step-${entry.step}-${entry.role}`;

  const frontmatter = buildFrontmatter(entry, agentName, host);

  const signature = `${SIGNATURE_PREFIX} hash:${skillHash} -->`;

  const header = [
    `# Specialized Subagent — Step ${entry.step} (${entry.role})`,
    '',
    `> Compiled from canonical skill: \`.agents/skills/${entry.skill}/SKILL.md\``,
    '> Dispatched by `ws-spec-to-pr` / `ws-spec-to-pr-lite` via `dispatch-agent`.',
    '> All domain instructions, behavioral invariants, checklists, and output schemas are pre-compiled into this system prompt.',
    '',
  ].join('\n');

  const rewrittenBody = rewriteSkillLinksForProjection(body, entry.skill);
  const productReadonlyBlock = entry.productReadonly ? `${PRODUCT_READONLY_BLOCK}\n` : '';
  const content = `${frontmatter}\n\n${signature}\n\n${header}${PATH_TOKENS_NOTE_BLOCK}\n${productReadonlyBlock}${rewrittenBody}\n\n${STEP_OUTPUT_SCHEMA_BLOCK}`;
  return { filename: `${agentName}.md`, content, skillHash, agentName };
}

function normalizeForCompare(content) {
  return normalizeNewlines(content).trim();
}

function runClean(targetDir, prefix, jsonMode, host = 'cursor') {
  const removed = [];
  const skipped = [];

  if (fs.existsSync(targetDir)) {
    const files = fs.readdirSync(targetDir);
    for (const file of files) {
      if (!file.endsWith('.md')) continue;
      const fullPath = path.join(targetDir, file);
      if (file.startsWith(`${prefix}-step-`)) {
        const text = fs.readFileSync(fullPath, 'utf8');
        if (text.includes(SIGNATURE_PREFIX)) {
          fs.unlinkSync(fullPath);
          removed.push(file);
          continue;
        }
      }
      skipped.push(file);
    }
  }

  const result = {
    ok: true,
    action: 'clean',
    targetDir,
    removedCount: removed.length,
    removed,
    preservedCustomCount: skipped.length,
    preservedCustom: skipped,
  };

  const iso = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  if (jsonMode) {
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  } else {
    process.stdout.write(`clean-host-agents | host=${host} | removed=${removed.length} | ${iso}\n`);
    if (removed.length > 0) {
      process.stdout.write(`Removed ${removed.length} compiled agent file(s) from ${targetDir}\n`);
    } else {
      process.stdout.write(`No compiled agent files found to clean in ${targetDir}\n`);
    }
  }

  return 0;
}

function runCheck(targetDir, agents, jsonMode) {
  const missing = [];
  const drifting = [];
  const okAgents = [];

  for (const agent of agents) {
    const targetFile = path.join(targetDir, agent.filename);
    if (!fs.existsSync(targetFile)) {
      missing.push(agent.filename);
      continue;
    }
    const onDiskText = fs.readFileSync(targetFile, 'utf8');
    const expectedSignature = `hash:${agent.skillHash}`;
    const contentMatch = normalizeForCompare(onDiskText) === normalizeForCompare(agent.content);
    if (!onDiskText.includes(SIGNATURE_PREFIX) || !onDiskText.includes(expectedSignature) || !contentMatch) {
      drifting.push(agent.filename);
    } else {
      okAgents.push(agent.filename);
    }
  }

  const isOk = missing.length === 0 && drifting.length === 0;
  const result = {
    ok: isOk,
    action: 'check',
    targetDir,
    totalAgents: agents.length,
    matchingCount: okAgents.length,
    missing,
    drifting,
  };

  if (jsonMode) {
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  } else {
    if (isOk) {
      process.stdout.write(`CHECK OK: All ${agents.length} compiled host subagents are present and up to date.\n`);
    } else {
      if (missing.length > 0) {
        process.stderr.write(`CHECK FAILED: Missing compiled agent(s):\n  - ${missing.join('\n  - ')}\n`);
      }
      if (drifting.length > 0) {
        process.stderr.write(`CHECK FAILED: Stale or drifting compiled agent(s):\n  - ${drifting.join('\n  - ')}\n`);
      }
    }
  }

  return isOk ? 0 : 1;
}

function runCompile(targetDir, agents, force, host, jsonMode) {
  fs.mkdirSync(targetDir, { recursive: true });

  const collisions = [];
  for (const agent of agents) {
    const targetFile = path.join(targetDir, agent.filename);
    if (fs.existsSync(targetFile)) {
      const existingText = fs.readFileSync(targetFile, 'utf8');
      if (!existingText.includes(SIGNATURE_PREFIX) && !force) {
        collisions.push(agent.filename);
      }
    }
  }
  if (collisions.length > 0) {
    const err = new Error(
      `refusing to overwrite non-generated custom agent(s): ${collisions.join(', ')} without --force.`,
    );
    err.collisions = collisions;
    throw err;
  }

  const compiled = [];
  const skippedIdentical = [];
  for (const agent of agents) {
    const targetFile = path.join(targetDir, agent.filename);
    if (fs.existsSync(targetFile)) {
      const existingText = fs.readFileSync(targetFile, 'utf8');
      if (normalizeForCompare(existingText) === normalizeForCompare(agent.content)) {
        skippedIdentical.push(agent.filename);
        continue;
      }
    }
    fs.writeFileSync(targetFile, agent.content, 'utf8');
    compiled.push(agent.filename);
  }

  const iso = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  const result = {
    ok: true,
    action: 'compile',
    host,
    targetDir,
    count: compiled.length,
    totalAgents: agents.length,
    compiled,
    skippedIdentical,
    skippedIdenticalCount: skippedIdentical.length,
    timestamp: iso,
  };

  if (jsonMode) {
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  } else {
    process.stdout.write(`compiled-host-agents | host=${host} | count=${compiled.length} | status=ok | ${iso}\n`);
    process.stdout.write(`Successfully compiled ${compiled.length} specialized subagents into ${targetDir}\n`);
  }

  return 0;
}

function main() {
  const options = parseArgs(process.argv);
  if (options.help) {
    process.stdout.write(
      'Usage: node compile_host_subagents.cjs [--repo-root DIR] [--host <cursor|claude|generic|auto>] [--prefix <name>] [--clean] [--check] [--json] [--force]\n',
    );
    process.exit(0);
  }

  try {
    const context = resolveConsumerContext({ repoRoot: options.repoRoot || undefined, scriptFile: SCRIPT_FILE });
    const repoRoot = context.repoRoot;

    let config = {};
    if (fs.existsSync(context.configPath)) {
      try {
        config = JSON.parse(fs.readFileSync(context.configPath, 'utf8'));
      } catch {
        config = {};
      }
    }

    const host = resolveHostTarget(repoRoot, options.host, config);
    const targetDir = resolveHostDirectory(repoRoot, host);
    const prefix = validateAgentPrefix(options.prefix || config?.defaults?.specializedSubagents?.agentPrefix || 'ws');

    if (options.clean) {
      const exitCode = runClean(targetDir, prefix, options.json, host);
      process.exit(exitCode);
    }

    const agents = STEP_SKILL_MAP.map((entry) => {
      const skillPath = resolveSkillMdPath(context, entry.skill);
      return compileAgentContent(entry, skillPath, prefix, host);
    });

    if (options.check) {
      const exitCode = runCheck(targetDir, agents, options.json);
      process.exit(exitCode);
    }

    const exitCode = runCompile(targetDir, agents, options.force, host, options.json);
    process.exit(exitCode);
  } catch (err) {
    if (options.json) {
      const errObj = {
        ok: false,
        error: err.message,
        collisionCount: err.collisions ? err.collisions.length : undefined,
        collisions: err.collisions || undefined,
      };
      process.stdout.write(JSON.stringify(errObj, null, 2) + '\n');
    } else {
      process.stderr.write(`ERROR: ${err.message}\n`);
    }
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  STEP_SKILL_MAP,
  SUPPORTED_HOSTS,
  SIGNATURE_PREFIX,
  AGENT_PREFIX_RE,
  validateAgentPrefix,
  normalizeNewlines,
  normalizeForCompare,
  rewriteSkillLinksForProjection,
  buildFrontmatter,
  resolveHostTarget,
  resolveHostDirectory,
  compileAgentContent,
  runClean,
  runCheck,
  runCompile,
};
