#!/usr/bin/env node
'use strict';

/**
 * Seed the generator-managed consumer skill body (blank skeleton).
 * Writes only when missing; never overwrites; --dry-run writes nothing.
 *
 * Usage:
 *   node seed_generated_skill.cjs --repo-root <dir> [--dry-run]
 */

const fs = require('fs');
const path = require('path');

const GENERATED_ID = 'ws-project-patterns';

const SKELETON = `---
name: ws-project-patterns
description: Consumer project patterns (generator-managed).
---

# ws-project-patterns

> When this skill is loaded, output "ws-project-patterns loaded."

## Patterns

- (none yet — the generator appends harvested bullets with evidence pointers)

## Anti-patterns

- (none yet)

## Maintenance

Regenerated by \`ws-patterns-generator\` runs. Human edits are preserved unless a run retires them (see run summaries). Opt out: \`stop ws-project-patterns\`.
`;

function usage(exitCode) {
  process.stderr.write('Usage: node seed_generated_skill.cjs --repo-root <dir> [--dry-run]\n');
  process.exit(exitCode);
}

function parseArgs(argv) {
  const options = { repoRoot: null, dryRun: false };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--repo-root') {
      options.repoRoot = argv[i + 1];
      i += 1;
    } else if (arg === '--dry-run') {
      options.dryRun = true;
    } else if (arg === '--help' || arg === '-h') {
      usage(0);
    } else {
      process.stderr.write(`Unknown flag: ${arg}\n`);
      usage(2);
    }
  }
  if (typeof options.repoRoot !== 'string' || !options.repoRoot.trim()) {
    process.stderr.write('Missing required --repo-root <dir>\n');
    usage(2);
  }
  return options;
}

function resolveTarget(repoRoot) {
  const root = path.resolve(repoRoot);
  let stat = null;
  try {
    stat = fs.statSync(root);
  } catch {
    stat = null;
  }
  if (!stat || !stat.isDirectory()) {
    process.stderr.write(`Not a directory: ${repoRoot}\n`);
    process.exit(1);
  }
  let skillsRel = '.agents/skills';
  try {
    const configPath = path.join(root, '.ws', 'config.json');
    if (fs.existsSync(configPath)) {
      const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      const configured = config && config.pathTokens && config.pathTokens.skillsRoot;
      if (typeof configured === 'string' && configured.trim()) skillsRel = configured.trim();
    }
  } catch {
    skillsRel = '.agents/skills';
  }
  const skillsRoot = path.resolve(root, skillsRel);
  const target = path.join(skillsRoot, GENERATED_ID, 'SKILL.md');
  const contained = target === skillsRoot || target.startsWith(skillsRoot + path.sep);
  if (!contained || !target.startsWith(root + path.sep)) {
    process.stderr.write('Refusing to write outside the repo skills root\n');
    process.exit(1);
  }
  return { root, target };
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  const { root, target } = resolveTarget(options.repoRoot);
  const rel = path.relative(root, target).split(path.sep).join('/');
  if (options.dryRun) {
    process.stdout.write(`planned: ${rel}\n`);
    return;
  }
  if (fs.existsSync(target)) {
    process.stdout.write(`unchanged: ${rel}\n`);
    return;
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, SKELETON + '\n', 'utf8');
  process.stdout.write(`written: ${rel}\n`);
}

main();
