#!/usr/bin/env node
'use strict';

/**
 * Seed the generator-managed consumer skill body (blank skeleton).
 * Writes only when missing; never overwrites; --dry-run writes nothing.
 *
 * Usage:
 *   node seed_generated_skill.cjs --repo-root <dir> [--dry-run]
 */

const fs = require('fs');
const path = require('path');

const GENERATED_ID = 'ws-project-patterns';

function loadHubResolver() {
  // Single-sourced hub root (spec 0115, AC1): resolved against this
  // script's own skills tree so SKILL.md and scripts stay the same version.
  const candidate = path.join(__dirname, '..', '..', 'ws-shared', 'runtime', 'scripts', 'resolve_hub_root.cjs');
  try {
    return require(candidate);
  } catch (err) {
    process.stderr.write(`Missing hub resolver ${candidate}: ${err.message}\n`);
    process.exit(1);
  }
}

const SKELETON = `---
name: ws-project-patterns
description: Consumer project patterns (generator-managed).
---

# ws-project-patterns

> When this skill is loaded, output "ws-project-patterns loaded."

## Patterns

- (none yet — the generator appends harvested bullets with evidence pointers)

## Anti-patterns

- (none yet)

## Maintenance

Regenerated by \`ws-patterns-generator\` runs. Human edits are preserved unless a run retires them (see run summaries). Opt out: \`stop ws-project-patterns\`.
`;

function usage(exitCode) {
  process.stderr.write('Usage: node seed_generated_skill.cjs --repo-root <dir> [--dry-run]\n');
  process.exit(exitCode);
}

function parseArgs(argv) {
  const options = { repoRoot: null, dryRun: false };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--repo-root') {
      options.repoRoot = argv[i + 1];
      i += 1;
    } else if (arg === '--dry-run') {
      options.dryRun = true;
    } else if (arg === '--help' || arg === '-h') {
      usage(0);
    } else {
      process.stderr.write(`Unknown flag: ${arg}\n`);
      usage(2);
    }
  }
  if (typeof options.repoRoot !== 'string' || !options.repoRoot.trim()) {
    process.stderr.write('Missing required --repo-root <dir>\n');
    usage(2);
  }
  return options;
}

function realpathLoose(candidate) {
  // Resolve symlinks through the deepest existing ancestor so missing-leaf
  // paths still get symlink-resolved parents (realpathSync throws on ENOENT).
  // lstat (not exists) so a link counts as existing even when its target does
  // not; a link that cannot be resolved fails closed (null) instead of passing
  // a lexical containment check.
  const rest = [];
  let existing = candidate;
  for (;;) {
    try {
      fs.lstatSync(existing);
      break;
    } catch {
      // keep walking up past missing leaves
    }
    rest.unshift(path.basename(existing));
    const parent = path.dirname(existing);
    if (parent === existing) return null;
    existing = parent;
  }
  try {
    return path.join(fs.realpathSync(existing), ...rest);
  } catch {
    return null;
  }
}

function resolveTarget(repoRoot) {
  const root = path.resolve(repoRoot);
  let stat = null;
  try {
    stat = fs.statSync(root);
  } catch {
    stat = null;
  }
  if (!stat || !stat.isDirectory()) {
    process.stderr.write(`Not a directory: ${repoRoot}\n`);
    process.exit(1);
  }
  // Generated pattern bodies are consumer-owned hub content: they live under
  // the configured project hub (single-sourced resolver: bootstrap
  // <repo>/.ws/config.json, then pathTokens.sharedDir, else .ws), never in
  // the published skills tree.
  let hubRoot;
  try {
    hubRoot = loadHubResolver().resolveHubRoot(root).hubRoot;
  } catch (err) {
    process.stderr.write(`Refusing unusable hub root: ${err.code || 'HUB_ERROR'}: ${err.message} (fix pathTokens.sharedDir in .ws/config.json)\n`);
    process.exit(1);
  }
  const target = path.join(hubRoot, GENERATED_ID, 'SKILL.md');
  const contained = target.startsWith(hubRoot + path.sep) && target.startsWith(root + path.sep);
  if (!contained) {
    process.stderr.write('Refusing to write outside the repo skills root\n');
    process.exit(1);
  }
  // Symlink-aware gate: lexical prefix checks cannot see directory links, so
  // re-verify containment on resolved real paths before any write lands. The
  // full target path is resolved (not rebuilt from a lexical leaf): a linked
  // parent directory or a dangling SKILL.md symlink would otherwise stay
  // lexically inside while writes follow the link out. Unresolvable paths fail
  // closed.
  const rootReal = fs.realpathSync(root);
  const targetReal = realpathLoose(target);
  if (!targetReal || !targetReal.startsWith(rootReal + path.sep)) {
    process.stderr.write('Refusing to write outside the repo skills root\n');
    process.exit(1);
  }
  return { root, target };
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  const { root, target } = resolveTarget(options.repoRoot);
  const rel = path.relative(root, target).split(path.sep).join('/');
  if (options.dryRun) {
    process.stdout.write(`planned: ${rel}\n`);
    return;
  }
  if (fs.existsSync(target)) {
    process.stdout.write(`unchanged: ${rel}\n`);
    return;
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, SKELETON + '\n', 'utf8');
  process.stdout.write(`written: ${rel}\n`);
}

main();
